defmodule SdrAgent.Repo.Migrations.S9aReplies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:replies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :message_id, :text, null: false
      add :in_reply_to, :text
      add :match_status, :text, null: false
      add :from_email, :citext, null: false
      add :to_email, :citext, null: false
      add :subject, :text
      add :body_text, :text, null: false
      add :body_sha256, :binary, null: false
      add :received_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "replies_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:replies, [:tenant_id, :message_id],
             name: "replies_unique_message_id_index"
           )

    alter table(:replies) do
      add :webhook_event_id, :uuid, null: false
    end

    create unique_index(:replies, [:webhook_event_id], name: "replies_unique_webhook_event_index")

    alter table(:replies) do
      add :delivery_operation_id,
          references(:delivery_operations,
            column: :id,
            name: "replies_delivery_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :contact_id,
          references(:contacts,
            column: :id,
            name: "replies_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :lead_id,
          references(:leads,
            column: :id,
            name: "replies_lead_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :enrollment_id,
          references(:campaign_enrollments,
            column: :id,
            name: "replies_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    alter table(:delivery_receipts) do
      add :webhook_event_id, :uuid
    end

    alter table(:suppressions) do
      add :reply_id,
          references(:replies,
            column: :id,
            name: "suppressions_reply_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :webhook_event_id, :uuid
    end

    drop_if_exists constraint(:suppressions, :suppressions_reply_source)

    create table(:webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:replies) do
      modify :webhook_event_id,
             references(:webhook_events,
               column: :id,
               name: "replies_webhook_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:replies, :replies_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:replies, :replies_match_status,
             check: """
               match_status IN ('matched', 'unmatched')
             """
           )

    create constraint(:replies, :replies_match_columns,
             check: """
               (match_status = 'matched' AND delivery_operation_id IS NOT NULL AND contact_id IS NOT NULL AND lead_id IS NOT NULL AND enrollment_id IS NOT NULL) OR (match_status = 'unmatched' AND delivery_operation_id IS NULL AND contact_id IS NULL AND lead_id IS NULL AND enrollment_id IS NULL)
             """
           )

    execute("""
    CREATE FUNCTION replies_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER replies_guard_row BEFORE UPDATE OR DELETE ON replies FOR EACH ROW EXECUTE FUNCTION replies_append_only()
    """)

    execute("""
    CREATE TRIGGER replies_guard_truncate BEFORE TRUNCATE ON replies FOR EACH STATEMENT EXECUTE FUNCTION replies_append_only()
    """)

    execute("""
    ALTER TABLE replies ADD CONSTRAINT replies_body_sha256_payload_fkey FOREIGN KEY (tenant_id, body_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    alter table(:delivery_receipts) do
      modify :webhook_event_id,
             references(:webhook_events,
               column: :id,
               name: "delivery_receipts_webhook_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:suppressions) do
      modify :webhook_event_id,
             references(:webhook_events,
               column: :id,
               name: "suppressions_webhook_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:suppressions, :suppressions_reply_source,
             check: """
               reason <> 'unsubscribe_reply' OR (decision_id IS NOT NULL AND reply_id IS NOT NULL)
             """
           )

    create constraint(:suppressions, :suppressions_link_source,
             check: """
               reason <> 'unsubscribe_link' OR webhook_event_id IS NOT NULL
             """
           )

    create constraint(:suppressions, :suppressions_complaint_source,
             check: """
               reason <> 'complaint' OR webhook_event_id IS NOT NULL
             """
           )

    alter table(:webhook_events) do
      add :provider, :text, null: false
      add :event_type, :text, null: false
      add :external_event_id, :text, null: false
      add :signature_verdict, :text, null: false
      add :signature_key_id, :text
      add :signed_timestamp, :utc_datetime_usec
      add :raw_body_sha256, :binary, null: false
      add :headers, :map, null: false, default: %{}
      add :processing_status, :text, null: false
      add :processed_at, :utc_datetime_usec
      add :received_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "webhook_events_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :failure_id,
          references(:failures,
            column: :id,
            name: "webhook_events_failure_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:webhook_events, [:tenant_id, :provider, :external_event_id],
             name: "webhook_events_unique_valid_event_index",
             where: "(signature_verdict = 'valid')"
           )

    create constraint(:webhook_events, :webhook_events_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:webhook_events, :webhook_events_provider,
             check: """
               provider IN ('capture_sim')
             """
           )

    create constraint(:webhook_events, :webhook_events_event_type,
             check: """
               event_type IN ('reply', 'unsubscribe', 'bounce', 'delivered', 'complaint')
             """
           )

    create constraint(:webhook_events, :webhook_events_verdict,
             check: """
               signature_verdict IN ('valid', 'invalid', 'missing', 'stale')
             """
           )

    create constraint(:webhook_events, :webhook_events_status,
             check: """
               processing_status IN ('received', 'processed', 'failed', 'rejected')
             """
           )

    create constraint(:webhook_events, :webhook_events_rejected_iff_not_valid,
             check: """
               (signature_verdict = 'valid') = (processing_status <> 'rejected')
             """
           )

    execute("""
    CREATE FUNCTION webhook_events_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.processing_status IN ('processed', 'rejected') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['processing_status', 'processed_at', 'failure_id', 'updated_at']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['processing_status', 'processed_at', 'failure_id', 'updated_at']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER webhook_events_guard_row BEFORE UPDATE OR DELETE ON webhook_events FOR EACH ROW EXECUTE FUNCTION webhook_events_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER webhook_events_guard_truncate BEFORE TRUNCATE ON webhook_events FOR EACH STATEMENT EXECUTE FUNCTION webhook_events_terminal_immutable()
    """)

    execute("""
    ALTER TABLE webhook_events ADD CONSTRAINT webhook_events_raw_body_sha256_payload_fkey FOREIGN KEY (tenant_id, raw_body_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)
  end

  def down do
    execute("""
    ALTER TABLE webhook_events DROP CONSTRAINT webhook_events_raw_body_sha256_payload_fkey
    """)

    execute("""
    DROP TRIGGER webhook_events_guard_truncate ON webhook_events
    """)

    execute("""
    DROP TRIGGER webhook_events_guard_row ON webhook_events
    """)

    execute("""
    DROP FUNCTION webhook_events_terminal_immutable()
    """)

    drop_if_exists constraint(:webhook_events, :webhook_events_rejected_iff_not_valid)

    drop_if_exists constraint(:webhook_events, :webhook_events_status)

    drop_if_exists constraint(:webhook_events, :webhook_events_verdict)

    drop_if_exists constraint(:webhook_events, :webhook_events_event_type)

    drop_if_exists constraint(:webhook_events, :webhook_events_provider)

    drop_if_exists constraint(:webhook_events, :webhook_events_trace_ids)

    drop constraint(:webhook_events, "webhook_events_failure_id_fkey")

    drop constraint(:webhook_events, "webhook_events_tenant_id_fkey")

    drop_if_exists unique_index(:webhook_events, [:tenant_id, :provider, :external_event_id],
                     name: "webhook_events_unique_valid_event_index"
                   )

    alter table(:webhook_events) do
      remove :failure_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :received_at
      remove :processed_at
      remove :processing_status
      remove :headers
      remove :raw_body_sha256
      remove :signed_timestamp
      remove :signature_key_id
      remove :signature_verdict
      remove :external_event_id
      remove :event_type
      remove :provider
    end

    drop_if_exists constraint(:suppressions, :suppressions_complaint_source)

    drop_if_exists constraint(:suppressions, :suppressions_link_source)

    drop_if_exists constraint(:suppressions, :suppressions_reply_source)

    drop constraint(:suppressions, "suppressions_webhook_event_id_fkey")

    drop constraint(:suppressions, "suppressions_reply_id_fkey")

    alter table(:suppressions) do
      modify :webhook_event_id, :uuid
    end

    drop constraint(:delivery_receipts, "delivery_receipts_webhook_event_id_fkey")

    alter table(:delivery_receipts) do
      modify :webhook_event_id, :uuid
    end

    execute("""
    ALTER TABLE replies DROP CONSTRAINT replies_body_sha256_payload_fkey
    """)

    execute("""
    DROP TRIGGER replies_guard_truncate ON replies
    """)

    execute("""
    DROP TRIGGER replies_guard_row ON replies
    """)

    execute("""
    DROP FUNCTION replies_append_only()
    """)

    drop_if_exists constraint(:replies, :replies_match_columns)

    drop_if_exists constraint(:replies, :replies_match_status)

    drop_if_exists constraint(:replies, :replies_trace_ids)

    drop constraint(:replies, "replies_enrollment_id_fkey")

    drop constraint(:replies, "replies_lead_id_fkey")

    drop constraint(:replies, "replies_contact_id_fkey")

    drop constraint(:replies, "replies_delivery_operation_id_fkey")

    drop constraint(:replies, "replies_webhook_event_id_fkey")

    drop constraint(:replies, "replies_tenant_id_fkey")

    alter table(:replies) do
      modify :webhook_event_id, :uuid
    end

    drop table(:webhook_events)

    create constraint(:suppressions, :suppressions_reply_source,
             check: """
               reason <> 'unsubscribe_reply' OR decision_id IS NOT NULL
             """
           )

    alter table(:suppressions) do
      remove :webhook_event_id
      remove :reply_id
    end

    alter table(:delivery_receipts) do
      remove :webhook_event_id
    end

    alter table(:replies) do
      remove :enrollment_id
      remove :lead_id
      remove :contact_id
      remove :delivery_operation_id
    end

    drop_if_exists unique_index(:replies, [:webhook_event_id],
                     name: "replies_unique_webhook_event_index"
                   )

    alter table(:replies) do
      remove :webhook_event_id
    end

    drop_if_exists unique_index(:replies, [:tenant_id, :message_id],
                     name: "replies_unique_message_id_index"
                   )

    drop table(:replies)
  end
end
