defmodule SdrAgent.Repo.Migrations.S3AuditKernel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :name, :text, null: false
      add :version, :bigint, null: false
      add :module, :text, null: false
      add :definition, :map, null: false
      add :definition_sha256, :binary, null: false
      add :status, :text, null: false, default: "active"
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false
    end

    create unique_index(:agent_definitions, [:tenant_id, :name, :version],
             name: "agent_definitions_unique_name_version_index"
           )

    create table(:agent_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :lead_id, :uuid
      add :campaign_id, :uuid
      add :trigger_signal_type, :text, null: false
      add :trigger_signal_id, :text, null: false
      add :correlation_id, :uuid, null: false
      add :phase, :text, null: false
      add :status, :text, null: false, default: "queued"
      add :budget, :map, null: false
      add :operation_id, :uuid
      add :status_reason, :text
      add :failure_reason, :text
      add :attention_failure_id, :uuid
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false

      add :agent_definition_id,
          references(:agent_definitions,
            column: :id,
            name: "agent_runs_agent_definition_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :retry_of_id,
          references(:agent_runs,
            column: :id,
            name: "agent_runs_retry_of_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:audit_accesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :actor_type, :text, null: false
      add :actor_id, :text, null: false
      add :access_kind, :text, null: false
      add :target_resource, :text, null: false
      add :target_ref, :text, null: false
      add :purpose, :text
      add :accessed_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false
      add :audit_event_id, :uuid, null: false
    end

    create table(:audit_chain_heads, primary_key: false) do
      add :last_sequence, :bigint, null: false
      add :last_event_hash, :binary, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false, primary_key: true
    end

    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:audit_accesses) do
      modify :audit_event_id,
             references(:audit_events,
               column: :id,
               name: "audit_accesses_audit_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:audit_events) do
      add :sequence, :bigint, null: false
      add :prev_hash, :binary, null: false
      add :event_hash, :binary, null: false
      add :canonical_bytes, :binary, null: false
      add :canonicalization_version, :text, null: false
      add :hash_algorithm, :text, null: false
      add :event_type, :text, null: false
      add :category, :text, null: false
      add :subject_resource, :text
      add :subject_id, :text
      add :action, :text
      add :payload, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false
      add :clock_source, :text, null: false
      add :actor_type, :text, null: false
      add :actor_id, :text
      add :actor_role, :text
      add :authorization, :map, null: false
      add :version_refs, :map, null: false, default: %{}
      add :causation_id, :uuid
      add :correlation_id, :uuid
      add :idempotency_key, :text
      add :attempt, :bigint, null: false, default: 0
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :request_id, :text
      add :agent_run_id, :uuid
      add :decision_id, :uuid
      add :model_invocation_id, :uuid
      add :tool_invocation_id, :uuid
      add :inserted_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false
    end

    create unique_index(:audit_events, [:tenant_id, :event_hash],
             name: "audit_events_unique_event_hash_index"
           )

    create unique_index(:audit_events, [:tenant_id, :sequence],
             name: "audit_events_unique_sequence_index"
           )

    alter table(:audit_events) do
      add :provenance_snapshot_id, :uuid, null: false
    end

    create table(:decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :kind, :text, null: false
      add :mode, :text, null: false
      add :subject_resource, :text, null: false
      add :subject_id, :uuid, null: false
      add :input_refs, {:array, :map}, null: false, default: []
      add :inputs_sha256, :binary, null: false
      add :rule_id, :text
      add :rule_version, :text
      add :output_pointer, :text
      add :outcome, :text, null: false
      add :outcome_detail, :map, null: false, default: %{}
      add :rationale, :text
      add :confidence, :float
      add :decided_at, :utc_datetime_usec, null: false
      add :idempotency_key, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false
    end

    create unique_index(:decisions, [:tenant_id, :idempotency_key],
             name: "decisions_unique_idempotency_key_index"
           )

    alter table(:decisions) do
      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "decisions_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :model_invocation_id, :uuid
    end

    create table(:model_invocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:decisions) do
      modify :model_invocation_id,
             references(:model_invocations,
               column: :id,
               name: "decisions_model_invocation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:model_invocations) do
      add :sequence_in_run, :bigint, null: false
      add :purpose, :text, null: false
      add :provider, :text, null: false
      add :provider_version, :text, null: false
      add :model_id, :text, null: false
      add :model_catalog_entry, :map, null: false
      add :account_mode_ref, :text, null: false
      add :data_control_setting, :text, null: false
      add :parameters, :map, null: false, default: %{}
      add :prompt_template_id, :text, null: false
      add :prompt_template_version, :text, null: false
      add :prompt_template_sha256, :binary, null: false
      add :output_schema_id, :text, null: false
      add :output_schema_version, :text, null: false
      add :output_schema_sha256, :binary, null: false
      add :request_sha256, :binary, null: false
      add :response_sha256, :binary
      add :parsed_output, :map
      add :validation_status, :text, null: false, default: "pending"
      add :validation_errors, {:array, :map}, null: false, default: []
      add :refusal, :text
      add :error, :map
      add :usage, :map
      add :latency_ms, :bigint
      add :status, :text, null: false, default: "reserved"
      add :reserved_at, :utc_datetime_usec, null: false
      add :sent_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :idempotency_key, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false
    end

    create unique_index(:model_invocations, [:tenant_id, :idempotency_key],
             name: "model_invocations_unique_idempotency_key_index"
           )

    alter table(:model_invocations) do
      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "model_invocations_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:model_invocations, [:agent_run_id, :sequence_in_run],
             name: "model_invocations_unique_sequence_in_run_index"
           )

    create table(:payloads, primary_key: false) do
      add :sha256, :binary, null: false, primary_key: true
      add :byte_size, :bigint, null: false
      add :content_type, :text, null: false
      add :content, :binary, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false, primary_key: true
    end

    create table(:provenance_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:audit_events) do
      modify :provenance_snapshot_id,
             references(:provenance_snapshots,
               column: :id,
               name: "audit_events_provenance_snapshot_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:provenance_snapshots) do
      add :snapshot_sha256, :binary, null: false
      add :git_sha, :text, null: false
      add :git_dirty, :boolean, null: false
      add :mix_lock_sha256, :binary, null: false
      add :otp_release, :text, null: false
      add :erts_version, :text, null: false
      add :elixir_version, :text, null: false
      add :app_version, :text, null: false
      add :config_sha256, :binary, null: false
      add :canonicalization_version, :text, null: false
      add :schema_version, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :recorded_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
    end

    create unique_index(:provenance_snapshots, [:snapshot_sha256],
             name: "provenance_snapshots_unique_snapshot_index"
           )

    create constraint(:provenance_snapshots, :provenance_snapshots_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION provenance_snapshots_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER provenance_snapshots_guard_row BEFORE UPDATE OR DELETE ON provenance_snapshots FOR EACH ROW EXECUTE FUNCTION provenance_snapshots_append_only()
    """)

    execute("""
    CREATE TRIGGER provenance_snapshots_guard_truncate BEFORE TRUNCATE ON provenance_snapshots FOR EACH STATEMENT EXECUTE FUNCTION provenance_snapshots_append_only()
    """)

    create table(:retention_markers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :target_resource, :text, null: false
      add :target_ref, :text, null: false
      add :retention_class, :text, null: false
      add :legal_hold, :boolean, null: false, default: false
      add :reason, :text, null: false
      add :effective_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false

      add :supersedes_id,
          references(:retention_markers,
            column: :id,
            name: "retention_markers_supersedes_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:tenants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:agent_definitions) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "agent_definitions_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:agent_definitions, :agent_definitions_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:agent_definitions, :agent_definitions_status,
             check: """
               status IN ('active', 'retired')
             """
           )

    alter table(:agent_runs) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "agent_runs_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:agent_runs, :agent_runs_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:agent_runs, :agent_runs_status,
             check: """
               status IN ('queued', 'running', 'succeeded', 'failed', 'budget_exhausted', 'cancelled')
             """
           )

    create constraint(:agent_runs, :agent_runs_status_reason_required,
             check: """
               status NOT IN ('failed', 'budget_exhausted', 'cancelled') OR status_reason IS NOT NULL
             """
           )

    alter table(:audit_accesses) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "audit_accesses_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:audit_accesses, :audit_accesses_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION audit_accesses_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER audit_accesses_guard_row BEFORE UPDATE OR DELETE ON audit_accesses FOR EACH ROW EXECUTE FUNCTION audit_accesses_append_only()
    """)

    execute("""
    CREATE TRIGGER audit_accesses_guard_truncate BEFORE TRUNCATE ON audit_accesses FOR EACH STATEMENT EXECUTE FUNCTION audit_accesses_append_only()
    """)

    alter table(:audit_chain_heads) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "audit_chain_heads_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:audit_chain_heads, :audit_chain_heads_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:audit_chain_heads, :audit_chain_heads_hash_length,
             check: """
               octet_length(last_event_hash) = 32
             """
           )

    alter table(:audit_events) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "audit_events_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:audit_events, :audit_events_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:audit_events, :audit_events_sequence_positive,
             check: """
               sequence >= 1
             """
           )

    create constraint(:audit_events, :audit_events_sha256,
             check: """
               hash_algorithm = 'sha256'
             """
           )

    create constraint(:audit_events, :audit_events_hash_lengths,
             check: """
               octet_length(event_hash) = 32 AND octet_length(prev_hash) = 32
             """
           )

    execute("""
    CREATE FUNCTION audit_events_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER audit_events_guard_row BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()
    """)

    execute("""
    CREATE TRIGGER audit_events_guard_truncate BEFORE TRUNCATE ON audit_events FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only()
    """)

    alter table(:decisions) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "decisions_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:decisions, :decisions_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:decisions, :decisions_mode_provenance,
             check: """
               (mode = 'llm' AND model_invocation_id IS NOT NULL AND output_pointer IS NOT NULL AND rule_id IS NULL AND rule_version IS NULL) OR (mode = 'deterministic' AND rule_id IS NOT NULL AND rule_version IS NOT NULL AND model_invocation_id IS NULL AND output_pointer IS NULL)
             """
           )

    execute("""
    CREATE FUNCTION decisions_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER decisions_guard_row BEFORE UPDATE OR DELETE ON decisions FOR EACH ROW EXECUTE FUNCTION decisions_append_only()
    """)

    execute("""
    CREATE TRIGGER decisions_guard_truncate BEFORE TRUNCATE ON decisions FOR EACH STATEMENT EXECUTE FUNCTION decisions_append_only()
    """)

    alter table(:model_invocations) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "model_invocations_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:model_invocations, :model_invocations_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:model_invocations, :model_invocations_status,
             check: """
               status IN ('reserved', 'sent', 'completed', 'failed', 'unknown')
             """
           )

    execute("""
    CREATE FUNCTION model_invocations_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.status IN ('completed', 'failed', 'unknown') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['status', 'response_sha256', 'parsed_output', 'validation_status', 'validation_errors', 'refusal', 'error', 'usage', 'latency_ms', 'sent_at', 'completed_at', 'updated_at']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'response_sha256', 'parsed_output', 'validation_status', 'validation_errors', 'refusal', 'error', 'usage', 'latency_ms', 'sent_at', 'completed_at', 'updated_at']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER model_invocations_guard_row BEFORE UPDATE OR DELETE ON model_invocations FOR EACH ROW EXECUTE FUNCTION model_invocations_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER model_invocations_guard_truncate BEFORE TRUNCATE ON model_invocations FOR EACH STATEMENT EXECUTE FUNCTION model_invocations_terminal_immutable()
    """)

    alter table(:payloads) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "payloads_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:payloads, :payloads_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:payloads, :payloads_sha256_length,
             check: """
               octet_length(sha256) = 32 AND byte_size >= 0
             """
           )

    execute("""
    ALTER TABLE decisions ADD CONSTRAINT decisions_inputs_sha256_payload_fkey FOREIGN KEY (tenant_id, inputs_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    execute("""
    ALTER TABLE model_invocations ADD CONSTRAINT model_invocations_request_sha256_payload_fkey FOREIGN KEY (tenant_id, request_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    execute("""
    ALTER TABLE model_invocations ADD CONSTRAINT model_invocations_response_sha256_payload_fkey FOREIGN KEY (tenant_id, response_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    execute("""
    CREATE FUNCTION payloads_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER payloads_guard_row BEFORE UPDATE OR DELETE ON payloads FOR EACH ROW EXECUTE FUNCTION payloads_append_only()
    """)

    execute("""
    CREATE TRIGGER payloads_guard_truncate BEFORE TRUNCATE ON payloads FOR EACH STATEMENT EXECUTE FUNCTION payloads_append_only()
    """)

    alter table(:retention_markers) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "retention_markers_tenant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create unique_index(:retention_markers, [:tenant_id, :target_resource, :target_ref],
             name: "retention_markers_unique_root_index",
             where: "(supersedes_id IS NULL)"
           )

    create unique_index(:retention_markers, [:supersedes_id],
             name: "retention_markers_unique_supersedes_index",
             where: "(supersedes_id IS NOT NULL)"
           )

    create constraint(:retention_markers, :retention_markers_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION retention_markers_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER retention_markers_guard_row BEFORE UPDATE OR DELETE ON retention_markers FOR EACH ROW EXECUTE FUNCTION retention_markers_append_only()
    """)

    execute("""
    CREATE TRIGGER retention_markers_guard_truncate BEFORE TRUNCATE ON retention_markers FOR EACH STATEMENT EXECUTE FUNCTION retention_markers_append_only()
    """)

    alter table(:tenants) do
      add :slug, :text, null: false
      add :name, :text, null: false
      add :singleton, :boolean, null: false, default: true
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
    end

    create unique_index(:tenants, [:singleton], name: "tenants_unique_singleton_index")

    create unique_index(:tenants, [:slug], name: "tenants_unique_slug_index")

    create constraint(:tenants, :singleton_must_be_true,
             check: """
               singleton = true
             """
           )

    create constraint(:tenants, :tenants_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION tenants_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER tenants_guard_row BEFORE UPDATE OR DELETE ON tenants FOR EACH ROW EXECUTE FUNCTION tenants_append_only()
    """)

    execute("""
    CREATE TRIGGER tenants_guard_truncate BEFORE TRUNCATE ON tenants FOR EACH STATEMENT EXECUTE FUNCTION tenants_append_only()
    """)

    create table(:tool_invocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :sequence_in_run, :bigint, null: false
      add :action_module, :text, null: false
      add :action_version, :text, null: false
      add :input_sha256, :binary, null: false
      add :output_sha256, :binary
      add :status, :text, null: false, default: "started"
      add :error, :map
      add :external_request_refs, {:array, :map}, null: false, default: []
      add :started_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :idempotency_key, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "tool_invocations_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:tool_invocations, [:tenant_id, :idempotency_key],
             name: "tool_invocations_unique_idempotency_key_index"
           )

    alter table(:tool_invocations) do
      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "tool_invocations_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:tool_invocations, [:agent_run_id, :sequence_in_run],
             name: "tool_invocations_unique_sequence_in_run_index"
           )

    create constraint(:tool_invocations, :tool_invocations_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:tool_invocations, :tool_invocations_status,
             check: """
               status IN ('started', 'succeeded', 'failed', 'unknown')
             """
           )

    execute("""
    CREATE FUNCTION tool_invocations_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.status IN ('succeeded', 'failed', 'unknown') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['status', 'output_sha256', 'error', 'external_request_refs', 'finished_at', 'duration_ms', 'updated_at']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'output_sha256', 'error', 'external_request_refs', 'finished_at', 'duration_ms', 'updated_at']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER tool_invocations_guard_row BEFORE UPDATE OR DELETE ON tool_invocations FOR EACH ROW EXECUTE FUNCTION tool_invocations_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER tool_invocations_guard_truncate BEFORE TRUNCATE ON tool_invocations FOR EACH STATEMENT EXECUTE FUNCTION tool_invocations_terminal_immutable()
    """)

    execute("""
    ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_input_sha256_payload_fkey FOREIGN KEY (tenant_id, input_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    execute("""
    ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_output_sha256_payload_fkey FOREIGN KEY (tenant_id, output_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)
  end

  def down do
    execute("""
    ALTER TABLE tool_invocations DROP CONSTRAINT tool_invocations_output_sha256_payload_fkey
    """)

    execute("""
    ALTER TABLE tool_invocations DROP CONSTRAINT tool_invocations_input_sha256_payload_fkey
    """)

    execute("""
    DROP TRIGGER tool_invocations_guard_truncate ON tool_invocations
    """)

    execute("""
    DROP TRIGGER tool_invocations_guard_row ON tool_invocations
    """)

    execute("""
    DROP FUNCTION tool_invocations_terminal_immutable()
    """)

    drop_if_exists constraint(:tool_invocations, :tool_invocations_status)

    drop_if_exists constraint(:tool_invocations, :tool_invocations_trace_ids)

    drop constraint(:tool_invocations, "tool_invocations_agent_run_id_fkey")

    drop constraint(:tool_invocations, "tool_invocations_tenant_id_fkey")

    drop_if_exists unique_index(:tool_invocations, [:agent_run_id, :sequence_in_run],
                     name: "tool_invocations_unique_sequence_in_run_index"
                   )

    alter table(:tool_invocations) do
      remove :agent_run_id
    end

    drop_if_exists unique_index(:tool_invocations, [:tenant_id, :idempotency_key],
                     name: "tool_invocations_unique_idempotency_key_index"
                   )

    drop table(:tool_invocations)

    execute("""
    DROP TRIGGER tenants_guard_truncate ON tenants
    """)

    execute("""
    DROP TRIGGER tenants_guard_row ON tenants
    """)

    execute("""
    DROP FUNCTION tenants_append_only()
    """)

    drop_if_exists constraint(:tenants, :tenants_trace_ids)

    drop_if_exists constraint(:tenants, :singleton_must_be_true)

    drop_if_exists unique_index(:tenants, [:slug], name: "tenants_unique_slug_index")

    drop_if_exists unique_index(:tenants, [:singleton], name: "tenants_unique_singleton_index")

    alter table(:tenants) do
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :singleton
      remove :name
      remove :slug
    end

    execute("""
    DROP TRIGGER retention_markers_guard_truncate ON retention_markers
    """)

    execute("""
    DROP TRIGGER retention_markers_guard_row ON retention_markers
    """)

    execute("""
    DROP FUNCTION retention_markers_append_only()
    """)

    drop_if_exists constraint(:retention_markers, :retention_markers_trace_ids)

    drop constraint(:retention_markers, "retention_markers_supersedes_id_fkey")

    drop constraint(:retention_markers, "retention_markers_tenant_id_fkey")

    drop_if_exists unique_index(:retention_markers, [:supersedes_id],
                     name: "retention_markers_unique_supersedes_index"
                   )

    drop_if_exists unique_index(:retention_markers, [:tenant_id, :target_resource, :target_ref],
                     name: "retention_markers_unique_root_index"
                   )

    alter table(:retention_markers) do
      modify :tenant_id, :uuid
    end

    execute("""
    DROP TRIGGER payloads_guard_truncate ON payloads
    """)

    execute("""
    DROP TRIGGER payloads_guard_row ON payloads
    """)

    execute("""
    DROP FUNCTION payloads_append_only()
    """)

    execute("""
    ALTER TABLE model_invocations DROP CONSTRAINT model_invocations_response_sha256_payload_fkey
    """)

    execute("""
    ALTER TABLE model_invocations DROP CONSTRAINT model_invocations_request_sha256_payload_fkey
    """)

    execute("""
    ALTER TABLE decisions DROP CONSTRAINT decisions_inputs_sha256_payload_fkey
    """)

    drop_if_exists constraint(:payloads, :payloads_sha256_length)

    drop_if_exists constraint(:payloads, :payloads_trace_ids)

    drop constraint(:payloads, "payloads_tenant_id_fkey")

    alter table(:payloads) do
      modify :tenant_id, :uuid
    end

    execute("""
    DROP TRIGGER model_invocations_guard_truncate ON model_invocations
    """)

    execute("""
    DROP TRIGGER model_invocations_guard_row ON model_invocations
    """)

    execute("""
    DROP FUNCTION model_invocations_terminal_immutable()
    """)

    drop_if_exists constraint(:model_invocations, :model_invocations_status)

    drop_if_exists constraint(:model_invocations, :model_invocations_trace_ids)

    drop constraint(:model_invocations, "model_invocations_agent_run_id_fkey")

    drop constraint(:model_invocations, "model_invocations_tenant_id_fkey")

    alter table(:model_invocations) do
      modify :tenant_id, :uuid
    end

    execute("""
    DROP TRIGGER decisions_guard_truncate ON decisions
    """)

    execute("""
    DROP TRIGGER decisions_guard_row ON decisions
    """)

    execute("""
    DROP FUNCTION decisions_append_only()
    """)

    drop_if_exists constraint(:decisions, :decisions_mode_provenance)

    drop_if_exists constraint(:decisions, :decisions_trace_ids)

    drop constraint(:decisions, "decisions_model_invocation_id_fkey")

    drop constraint(:decisions, "decisions_agent_run_id_fkey")

    drop constraint(:decisions, "decisions_tenant_id_fkey")

    alter table(:decisions) do
      modify :tenant_id, :uuid
    end

    execute("""
    DROP TRIGGER audit_events_guard_truncate ON audit_events
    """)

    execute("""
    DROP TRIGGER audit_events_guard_row ON audit_events
    """)

    execute("""
    DROP FUNCTION audit_events_append_only()
    """)

    drop_if_exists constraint(:audit_events, :audit_events_hash_lengths)

    drop_if_exists constraint(:audit_events, :audit_events_sha256)

    drop_if_exists constraint(:audit_events, :audit_events_sequence_positive)

    drop_if_exists constraint(:audit_events, :audit_events_trace_ids)

    drop constraint(:audit_events, "audit_events_provenance_snapshot_id_fkey")

    drop constraint(:audit_events, "audit_events_tenant_id_fkey")

    alter table(:audit_events) do
      modify :tenant_id, :uuid
    end

    drop_if_exists constraint(:audit_chain_heads, :audit_chain_heads_hash_length)

    drop_if_exists constraint(:audit_chain_heads, :audit_chain_heads_trace_ids)

    drop constraint(:audit_chain_heads, "audit_chain_heads_tenant_id_fkey")

    alter table(:audit_chain_heads) do
      modify :tenant_id, :uuid
    end

    execute("""
    DROP TRIGGER audit_accesses_guard_truncate ON audit_accesses
    """)

    execute("""
    DROP TRIGGER audit_accesses_guard_row ON audit_accesses
    """)

    execute("""
    DROP FUNCTION audit_accesses_append_only()
    """)

    drop_if_exists constraint(:audit_accesses, :audit_accesses_trace_ids)

    drop constraint(:audit_accesses, "audit_accesses_audit_event_id_fkey")

    drop constraint(:audit_accesses, "audit_accesses_tenant_id_fkey")

    alter table(:audit_accesses) do
      modify :tenant_id, :uuid
    end

    drop_if_exists constraint(:agent_runs, :agent_runs_status_reason_required)

    drop_if_exists constraint(:agent_runs, :agent_runs_status)

    drop_if_exists constraint(:agent_runs, :agent_runs_trace_ids)

    drop constraint(:agent_runs, "agent_runs_retry_of_id_fkey")

    drop constraint(:agent_runs, "agent_runs_agent_definition_id_fkey")

    drop constraint(:agent_runs, "agent_runs_tenant_id_fkey")

    alter table(:agent_runs) do
      modify :tenant_id, :uuid
    end

    drop_if_exists constraint(:agent_definitions, :agent_definitions_status)

    drop_if_exists constraint(:agent_definitions, :agent_definitions_trace_ids)

    drop constraint(:agent_definitions, "agent_definitions_tenant_id_fkey")

    alter table(:agent_definitions) do
      modify :tenant_id, :uuid
    end

    drop table(:tenants)

    drop table(:retention_markers)

    execute("""
    DROP TRIGGER provenance_snapshots_guard_truncate ON provenance_snapshots
    """)

    execute("""
    DROP TRIGGER provenance_snapshots_guard_row ON provenance_snapshots
    """)

    execute("""
    DROP FUNCTION provenance_snapshots_append_only()
    """)

    drop_if_exists constraint(:provenance_snapshots, :provenance_snapshots_trace_ids)

    drop_if_exists unique_index(:provenance_snapshots, [:snapshot_sha256],
                     name: "provenance_snapshots_unique_snapshot_index"
                   )

    alter table(:provenance_snapshots) do
      remove :inserted_at
      remove :recorded_at
      remove :span_id
      remove :trace_id
      remove :schema_version
      remove :canonicalization_version
      remove :config_sha256
      remove :app_version
      remove :elixir_version
      remove :erts_version
      remove :otp_release
      remove :mix_lock_sha256
      remove :git_dirty
      remove :git_sha
      remove :snapshot_sha256
    end

    alter table(:audit_events) do
      modify :provenance_snapshot_id, :uuid
    end

    drop table(:provenance_snapshots)

    drop table(:payloads)

    drop_if_exists unique_index(:model_invocations, [:agent_run_id, :sequence_in_run],
                     name: "model_invocations_unique_sequence_in_run_index"
                   )

    alter table(:model_invocations) do
      remove :agent_run_id
    end

    drop_if_exists unique_index(:model_invocations, [:tenant_id, :idempotency_key],
                     name: "model_invocations_unique_idempotency_key_index"
                   )

    alter table(:model_invocations) do
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :idempotency_key
      remove :completed_at
      remove :sent_at
      remove :reserved_at
      remove :status
      remove :latency_ms
      remove :usage
      remove :error
      remove :refusal
      remove :validation_errors
      remove :validation_status
      remove :parsed_output
      remove :response_sha256
      remove :request_sha256
      remove :output_schema_sha256
      remove :output_schema_version
      remove :output_schema_id
      remove :prompt_template_sha256
      remove :prompt_template_version
      remove :prompt_template_id
      remove :parameters
      remove :data_control_setting
      remove :account_mode_ref
      remove :model_catalog_entry
      remove :model_id
      remove :provider_version
      remove :provider
      remove :purpose
      remove :sequence_in_run
    end

    alter table(:decisions) do
      modify :model_invocation_id, :uuid
    end

    drop table(:model_invocations)

    alter table(:decisions) do
      remove :model_invocation_id
      remove :agent_run_id
    end

    drop_if_exists unique_index(:decisions, [:tenant_id, :idempotency_key],
                     name: "decisions_unique_idempotency_key_index"
                   )

    drop table(:decisions)

    alter table(:audit_events) do
      remove :provenance_snapshot_id
    end

    drop_if_exists unique_index(:audit_events, [:tenant_id, :sequence],
                     name: "audit_events_unique_sequence_index"
                   )

    drop_if_exists unique_index(:audit_events, [:tenant_id, :event_hash],
                     name: "audit_events_unique_event_hash_index"
                   )

    alter table(:audit_events) do
      remove :tenant_id
      remove :inserted_at
      remove :tool_invocation_id
      remove :model_invocation_id
      remove :decision_id
      remove :agent_run_id
      remove :request_id
      remove :span_id
      remove :trace_id
      remove :attempt
      remove :idempotency_key
      remove :correlation_id
      remove :causation_id
      remove :version_refs
      remove :authorization
      remove :actor_role
      remove :actor_id
      remove :actor_type
      remove :clock_source
      remove :occurred_at
      remove :payload
      remove :action
      remove :subject_id
      remove :subject_resource
      remove :category
      remove :event_type
      remove :hash_algorithm
      remove :canonicalization_version
      remove :canonical_bytes
      remove :event_hash
      remove :prev_hash
      remove :sequence
    end

    alter table(:audit_accesses) do
      modify :audit_event_id, :uuid
    end

    drop table(:audit_events)

    drop table(:audit_chain_heads)

    drop table(:audit_accesses)

    drop table(:agent_runs)

    drop_if_exists unique_index(:agent_definitions, [:tenant_id, :name, :version],
                     name: "agent_definitions_unique_name_version_index"
                   )

    drop table(:agent_definitions)
  end
end
