defmodule SdrAgent.Repo.Migrations.S8bDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:delivery_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :idempotency_key, :text, null: false
      add :revision_content_sha256, :binary, null: false
      add :recipient_email, :citext, null: false
      add :provider, :text, null: false
      add :provider_message_id, :text
      add :send_quota_date, :date
      add :state, :text, null: false, default: "pending"
      add :attempt_count, :bigint, null: false, default: 0
      add :max_attempts, :bigint, null: false, default: 3
      add :not_before, :utc_datetime_usec
      add :requested_at, :utc_datetime_usec
      add :attempting_at, :utc_datetime_usec
      add :accepted_at, :utc_datetime_usec
      add :confirmed_at, :utc_datetime_usec
      add :unknown_since, :utc_datetime_usec
      add :rendered_sha256, :binary
      add :footer_template_version, :text
      add :last_error, :map
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "delivery_operations_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:delivery_operations, [:tenant_id, :idempotency_key],
             name: "delivery_operations_unique_idempotency_key_index"
           )

    alter table(:delivery_operations) do
      add :approval_id,
          references(:approvals,
            column: :id,
            name: "delivery_operations_approval_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:delivery_operations, [:approval_id],
             name: "delivery_operations_unique_approval_index"
           )

    alter table(:delivery_operations) do
      add :draft_id,
          references(:drafts,
            column: :id,
            name: "delivery_operations_draft_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :draft_revision_id,
          references(:draft_revisions,
            column: :id,
            name: "delivery_operations_draft_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :enrollment_id,
          references(:campaign_enrollments,
            column: :id,
            name: "delivery_operations_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "delivery_operations_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :recipient_contact_id,
          references(:contacts,
            column: :id,
            name: "delivery_operations_recipient_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :last_decision_id,
          references(:decisions,
            column: :id,
            name: "delivery_operations_last_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :attention_failure_id,
          references(:failures,
            column: :id,
            name: "delivery_operations_attention_failure_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:delivery_operations, [:tenant_id, :provider, :provider_message_id],
             name: "delivery_operations_unique_provider_message_index",
             where: "(provider_message_id IS NOT NULL)"
           )

    create constraint(:delivery_operations, :delivery_operations_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:delivery_operations, :delivery_operations_state,
             check: """
               state IN ('pending', 'attempting', 'accepted', 'unknown', 'failed_retryable', 'failed_permanent', 'delivered', 'bounced', 'cancelled')
             """
           )

    create constraint(:delivery_operations, :delivery_operations_capture_only,
             check: """
               provider IN ('capture')
             """
           )

    create constraint(:delivery_operations, :delivery_operations_attempts,
             check: """
               attempt_count >= 0 AND attempt_count <= max_attempts
             """
           )

    create constraint(:delivery_operations, :delivery_operations_accepted_has_message_id,
             check: """
               state NOT IN ('accepted', 'delivered', 'bounced') OR provider_message_id IS NOT NULL
             """
           )

    execute("""
    CREATE FUNCTION delivery_operations_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.state IN ('failed_permanent', 'delivered', 'bounced', 'cancelled') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['state', 'attempt_count', 'not_before', 'attempting_at', 'accepted_at', 'confirmed_at', 'unknown_since', 'provider_message_id', 'send_quota_date', 'rendered_sha256', 'footer_template_version', 'last_error', 'last_decision_id', 'attention_failure_id', 'updated_at']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['state', 'attempt_count', 'not_before', 'attempting_at', 'accepted_at', 'confirmed_at', 'unknown_since', 'provider_message_id', 'send_quota_date', 'rendered_sha256', 'footer_template_version', 'last_error', 'last_decision_id', 'attention_failure_id', 'updated_at']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER delivery_operations_guard_row BEFORE UPDATE OR DELETE ON delivery_operations FOR EACH ROW EXECUTE FUNCTION delivery_operations_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER delivery_operations_guard_truncate BEFORE TRUNCATE ON delivery_operations FOR EACH STATEMENT EXECUTE FUNCTION delivery_operations_terminal_immutable()
    """)

    execute("""
    ALTER TABLE delivery_operations ADD CONSTRAINT delivery_operations_rendered_sha256_payload_fkey FOREIGN KEY (tenant_id, rendered_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    create table(:send_quota_days, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :local_date, :date, null: false
      add :timezone, :text, null: false
      add :cap, :bigint, null: false
      add :consumed, :bigint, null: false, default: 0
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "send_quota_days_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:send_quota_days, [:tenant_id, :local_date],
             name: "send_quota_days_unique_day_index"
           )

    create constraint(:send_quota_days, :send_quota_days_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:send_quota_days, :send_quota_days_cap,
             check: """
               cap BETWEEN 1 AND 25
             """
           )

    create constraint(:send_quota_days, :send_quota_days_consumed,
             check: """
               consumed >= 0 AND consumed <= cap
             """
           )

    create table(:delivery_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :idempotency_key, :text, null: false
      add :kind, :text, null: false
      add :provider, :text, null: false
      add :provider_message_id, :text, null: false
      add :rendered_sha256, :binary, null: false
      add :response_sha256, :binary
      add :received_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "delivery_receipts_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :delivery_operation_id,
          references(:delivery_operations,
            column: :id,
            name: "delivery_receipts_delivery_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:delivery_receipts, [:delivery_operation_id, :kind],
             name: "delivery_receipts_unique_kind_index"
           )

    create constraint(:delivery_receipts, :delivery_receipts_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:delivery_receipts, :delivery_receipts_kind,
             check: """
               kind IN ('captured', 'accepted', 'delivered', 'bounced', 'reconciled')
             """
           )

    create constraint(:delivery_receipts, :delivery_receipts_capture_only,
             check: """
               provider IN ('capture')
             """
           )

    execute("""
    CREATE FUNCTION delivery_receipts_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER delivery_receipts_guard_row BEFORE UPDATE OR DELETE ON delivery_receipts FOR EACH ROW EXECUTE FUNCTION delivery_receipts_append_only()
    """)

    execute("""
    CREATE TRIGGER delivery_receipts_guard_truncate BEFORE TRUNCATE ON delivery_receipts FOR EACH STATEMENT EXECUTE FUNCTION delivery_receipts_append_only()
    """)

    execute("""
    ALTER TABLE delivery_receipts ADD CONSTRAINT delivery_receipts_rendered_sha256_payload_fkey FOREIGN KEY (tenant_id, rendered_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    alter table(:suppressions) do
      modify :delivery_operation_id,
             references(:delivery_operations,
               column: :id,
               name: "suppressions_delivery_operation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(:suppressions, "suppressions_delivery_operation_id_fkey")

    alter table(:suppressions) do
      modify :delivery_operation_id, :uuid
    end

    execute("""
    ALTER TABLE delivery_receipts DROP CONSTRAINT delivery_receipts_rendered_sha256_payload_fkey
    """)

    execute("""
    DROP TRIGGER delivery_receipts_guard_truncate ON delivery_receipts
    """)

    execute("""
    DROP TRIGGER delivery_receipts_guard_row ON delivery_receipts
    """)

    execute("""
    DROP FUNCTION delivery_receipts_append_only()
    """)

    drop_if_exists constraint(:delivery_receipts, :delivery_receipts_capture_only)

    drop_if_exists constraint(:delivery_receipts, :delivery_receipts_kind)

    drop_if_exists constraint(:delivery_receipts, :delivery_receipts_trace_ids)

    drop constraint(:delivery_receipts, "delivery_receipts_delivery_operation_id_fkey")

    drop constraint(:delivery_receipts, "delivery_receipts_tenant_id_fkey")

    drop_if_exists unique_index(:delivery_receipts, [:delivery_operation_id, :kind],
                     name: "delivery_receipts_unique_kind_index"
                   )

    drop table(:delivery_receipts)

    drop_if_exists constraint(:send_quota_days, :send_quota_days_consumed)

    drop_if_exists constraint(:send_quota_days, :send_quota_days_cap)

    drop_if_exists constraint(:send_quota_days, :send_quota_days_trace_ids)

    drop constraint(:send_quota_days, "send_quota_days_tenant_id_fkey")

    drop_if_exists unique_index(:send_quota_days, [:tenant_id, :local_date],
                     name: "send_quota_days_unique_day_index"
                   )

    drop table(:send_quota_days)

    execute("""
    ALTER TABLE delivery_operations DROP CONSTRAINT delivery_operations_rendered_sha256_payload_fkey
    """)

    execute("""
    DROP TRIGGER delivery_operations_guard_truncate ON delivery_operations
    """)

    execute("""
    DROP TRIGGER delivery_operations_guard_row ON delivery_operations
    """)

    execute("""
    DROP FUNCTION delivery_operations_terminal_immutable()
    """)

    drop_if_exists constraint(:delivery_operations, :delivery_operations_accepted_has_message_id)

    drop_if_exists constraint(:delivery_operations, :delivery_operations_attempts)

    drop_if_exists constraint(:delivery_operations, :delivery_operations_capture_only)

    drop_if_exists constraint(:delivery_operations, :delivery_operations_state)

    drop_if_exists constraint(:delivery_operations, :delivery_operations_trace_ids)

    drop constraint(:delivery_operations, "delivery_operations_attention_failure_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_last_decision_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_recipient_contact_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_campaign_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_enrollment_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_draft_revision_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_draft_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_approval_id_fkey")

    drop constraint(:delivery_operations, "delivery_operations_tenant_id_fkey")

    drop_if_exists unique_index(
                     :delivery_operations,
                     [:tenant_id, :provider, :provider_message_id],
                     name: "delivery_operations_unique_provider_message_index"
                   )

    alter table(:delivery_operations) do
      remove :attention_failure_id
      remove :last_decision_id
      remove :recipient_contact_id
      remove :campaign_id
      remove :enrollment_id
      remove :draft_revision_id
      remove :draft_id
    end

    drop_if_exists unique_index(:delivery_operations, [:approval_id],
                     name: "delivery_operations_unique_approval_index"
                   )

    alter table(:delivery_operations) do
      remove :approval_id
    end

    drop_if_exists unique_index(:delivery_operations, [:tenant_id, :idempotency_key],
                     name: "delivery_operations_unique_idempotency_key_index"
                   )

    drop table(:delivery_operations)
  end
end
