defmodule SdrAgent.Repo.Migrations.S8aOutreach do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :revision_content_sha256, :binary, null: false
      add :recipient_email, :citext, null: false
      add :approver_authored_revision, :boolean, null: false
      add :verdict, :text, null: false
      add :reason, :text
      add :status, :text, null: false
      add :decided_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :invalidated_reason, :text
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "approvals_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :draft_id, :uuid, null: false
      add :draft_revision_id, :uuid, null: false

      add :recipient_contact_id,
          references(:contacts,
            column: :id,
            name: "approvals_recipient_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "approvals_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :approver_id,
          references(:users,
            column: :id,
            name: "approvals_approver_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :revoked_by_id,
          references(:users,
            column: :id,
            name: "approvals_revoked_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:revision_citations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :kind, :text, null: false
      add :text, :text, null: false
      add :confidence, :float
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "revision_citations_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :draft_revision_id, :uuid, null: false

      add :evidence_claim_id,
          references(:evidence_claims,
            column: :id,
            name: "revision_citations_evidence_claim_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(
             :revision_citations,
             [:draft_revision_id, :evidence_claim_id, :kind, :text],
             name: "revision_citations_unique_citation_index"
           )

    create table(:draft_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:approvals) do
      modify :draft_revision_id,
             references(:draft_revisions,
               column: :id,
               name: "approvals_draft_revision_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:revision_citations) do
      modify :draft_revision_id,
             references(:draft_revisions,
               column: :id,
               name: "revision_citations_draft_revision_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:revision_citations, :revision_citations_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:revision_citations, :revision_citations_kind,
             check: """
               kind IN ('claim', 'personalization')
             """
           )

    execute("""
    CREATE FUNCTION revision_citations_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER revision_citations_guard_row BEFORE UPDATE OR DELETE ON revision_citations FOR EACH ROW EXECUTE FUNCTION revision_citations_append_only()
    """)

    execute("""
    CREATE TRIGGER revision_citations_guard_truncate BEFORE TRUNCATE ON revision_citations FOR EACH STATEMENT EXECUTE FUNCTION revision_citations_append_only()
    """)

    alter table(:draft_revisions) do
      add :revision_number, :bigint, null: false
      add :author_type, :text, null: false
      add :subject, :text, null: false
      add :body_text, :text, null: false
      add :angle, :text
      add :cta, :text
      add :risk_flags, {:array, :text}, null: false, default: []
      add :content_sha256, :binary, null: false
      add :canonicalization_version, :text, null: false
      add :diff_from_parent, :text
      add :diff_from_ai_baseline, :text
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "draft_revisions_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :draft_id, :uuid, null: false
    end

    create unique_index(:draft_revisions, [:draft_id, :revision_number],
             name: "draft_revisions_unique_number_index"
           )

    alter table(:draft_revisions) do
      add :parent_revision_id,
          references(:draft_revisions,
            column: :id,
            name: "draft_revisions_parent_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :ai_baseline_revision_id,
          references(:draft_revisions,
            column: :id,
            name: "draft_revisions_ai_baseline_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :author_user_id,
          references(:users,
            column: :id,
            name: "draft_revisions_author_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "draft_revisions_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :decision_id,
          references(:decisions,
            column: :id,
            name: "draft_revisions_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :model_invocation_id,
          references(:model_invocations,
            column: :id,
            name: "draft_revisions_model_invocation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:suppressions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :scope, :text, null: false
      add :value, :citext, null: false
      add :reason, :text, null: false
      add :delivery_operation_id, :uuid
      add :effective_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "suppressions_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:suppressions, [:tenant_id, :scope, :value],
             name: "suppressions_unique_value_index"
           )

    alter table(:suppressions) do
      add :created_by_user_id,
          references(:users,
            column: :id,
            name: "suppressions_created_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :decision_id,
          references(:decisions,
            column: :id,
            name: "suppressions_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:suppressions, :suppressions_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:suppressions, :suppressions_scope,
             check: """
               scope IN ('email', 'domain')
             """
           )

    create constraint(:suppressions, :suppressions_reason,
             check: """
               reason IN ('unsubscribe_link', 'unsubscribe_reply', 'hard_bounce', 'complaint', 'manual')
             """
           )

    create constraint(:suppressions, :suppressions_value_normalised,
             check: """
               value::text = lower(btrim(value::text)) AND value::text <> ''
             """
           )

    create constraint(:suppressions, :suppressions_reply_source,
             check: """
               reason <> 'unsubscribe_reply' OR decision_id IS NOT NULL
             """
           )

    create constraint(:suppressions, :suppressions_bounce_source,
             check: """
               reason <> 'hard_bounce' OR delivery_operation_id IS NOT NULL
             """
           )

    execute("""
    CREATE FUNCTION suppressions_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER suppressions_guard_row BEFORE UPDATE OR DELETE ON suppressions FOR EACH ROW EXECUTE FUNCTION suppressions_append_only()
    """)

    execute("""
    CREATE TRIGGER suppressions_guard_truncate BEFORE TRUNCATE ON suppressions FOR EACH STATEMENT EXECUTE FUNCTION suppressions_append_only()
    """)

    create table(:drafts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:approvals) do
      modify :draft_id,
             references(:drafts,
               column: :id,
               name: "approvals_draft_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create unique_index(:approvals, [:draft_id],
             name: "approvals_one_live_per_draft_index",
             where: "(status IN ('granted', 'consumed'))"
           )

    create constraint(:approvals, :approvals_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:approvals, :approvals_status,
             check: """
               status IN ('granted', 'consumed', 'rejected', 'revoked', 'invalidated')
             """
           )

    create constraint(:approvals, :approvals_verdict_status,
             check: """
               (verdict = 'approved' AND status IN ('granted', 'consumed', 'revoked', 'invalidated')) OR (verdict = 'rejected' AND status = 'rejected' AND reason IS NOT NULL)
             """
           )

    create constraint(:approvals, :approvals_revision_sha256_length,
             check: """
               octet_length(revision_content_sha256) = 32
             """
           )

    create constraint(:approvals, :approvals_invalidated_reason,
             check: """
               (status = 'invalidated') = (invalidated_reason IS NOT NULL)
             """
           )

    execute("""
    CREATE FUNCTION approvals_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.status IN ('consumed', 'rejected', 'revoked', 'invalidated') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['status', 'revoked_at', 'revoked_by_id', 'invalidated_reason', 'updated_at']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'revoked_at', 'revoked_by_id', 'invalidated_reason', 'updated_at']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER approvals_guard_row BEFORE UPDATE OR DELETE ON approvals FOR EACH ROW EXECUTE FUNCTION approvals_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER approvals_guard_truncate BEFORE TRUNCATE ON approvals FOR EACH STATEMENT EXECUTE FUNCTION approvals_terminal_immutable()
    """)

    alter table(:draft_revisions) do
      modify :draft_id,
             references(:drafts,
               column: :id,
               name: "draft_revisions_draft_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:draft_revisions, :draft_revisions_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:draft_revisions, :draft_revisions_content_sha256_length,
             check: """
               octet_length(content_sha256) = 32
             """
           )

    create constraint(:draft_revisions, :draft_revisions_provenance,
             check: """
               (author_type = 'agent' AND agent_run_id IS NOT NULL AND decision_id IS NOT NULL AND author_user_id IS NULL) OR (author_type = 'human' AND author_user_id IS NOT NULL AND parent_revision_id IS NOT NULL)
             """
           )

    create constraint(:draft_revisions, :draft_revisions_first_has_no_parent,
             check: """
               (revision_number = 1) = (parent_revision_id IS NULL)
             """
           )

    execute("""
    CREATE FUNCTION draft_revisions_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER draft_revisions_guard_row BEFORE UPDATE OR DELETE ON draft_revisions FOR EACH ROW EXECUTE FUNCTION draft_revisions_append_only()
    """)

    execute("""
    CREATE TRIGGER draft_revisions_guard_truncate BEFORE TRUNCATE ON draft_revisions FOR EACH STATEMENT EXECUTE FUNCTION draft_revisions_append_only()
    """)

    alter table(:drafts) do
      add :status, :text, null: false, default: "pending_review"
      add :status_reason, :text
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "drafts_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :lead_id,
          references(:leads,
            column: :id,
            name: "drafts_lead_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :enrollment_id,
          references(:campaign_enrollments,
            column: :id,
            name: "drafts_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :sequence_step_id,
          references(:sequence_steps,
            column: :id,
            name: "drafts_sequence_step_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "drafts_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :recipient_contact_id,
          references(:contacts,
            column: :id,
            name: "drafts_recipient_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :origin_agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "drafts_origin_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :current_revision_id,
          references(:draft_revisions,
            column: :id,
            name: "drafts_current_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:drafts, [:enrollment_id, :sequence_step_id],
             name: "drafts_one_open_per_step_index",
             where: "(status NOT IN ('rejected', 'cancelled', 'failed'))"
           )

    execute(
      "ALTER TABLE drafts ALTER CONSTRAINT drafts_current_revision_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    create constraint(:drafts, :drafts_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:drafts, :drafts_status,
             check: """
               status IN ('pending_review', 'queued', 'sent', 'failed', 'rejected', 'cancelled')
             """
           )

    execute("""
    CREATE FUNCTION drafts_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.status IN ('sent', 'failed', 'rejected', 'cancelled') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['status', 'status_reason', 'current_revision_id', 'updated_at']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'status_reason', 'current_revision_id', 'updated_at']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER drafts_guard_row BEFORE UPDATE OR DELETE ON drafts FOR EACH ROW EXECUTE FUNCTION drafts_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER drafts_guard_truncate BEFORE TRUNCATE ON drafts FOR EACH STATEMENT EXECUTE FUNCTION drafts_terminal_immutable()
    """)
  end

  def down do
    execute("""
    DROP TRIGGER drafts_guard_truncate ON drafts
    """)

    execute("""
    DROP TRIGGER drafts_guard_row ON drafts
    """)

    execute("""
    DROP FUNCTION drafts_terminal_immutable()
    """)

    drop_if_exists constraint(:drafts, :drafts_status)

    drop_if_exists constraint(:drafts, :drafts_trace_ids)

    drop constraint(:drafts, "drafts_current_revision_id_fkey")

    drop constraint(:drafts, "drafts_origin_agent_run_id_fkey")

    drop constraint(:drafts, "drafts_recipient_contact_id_fkey")

    drop constraint(:drafts, "drafts_campaign_id_fkey")

    drop constraint(:drafts, "drafts_sequence_step_id_fkey")

    drop constraint(:drafts, "drafts_enrollment_id_fkey")

    drop constraint(:drafts, "drafts_lead_id_fkey")

    drop constraint(:drafts, "drafts_tenant_id_fkey")

    drop_if_exists unique_index(:drafts, [:enrollment_id, :sequence_step_id],
                     name: "drafts_one_open_per_step_index"
                   )

    alter table(:drafts) do
      remove :current_revision_id
      remove :origin_agent_run_id
      remove :recipient_contact_id
      remove :campaign_id
      remove :sequence_step_id
      remove :enrollment_id
      remove :lead_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :status_reason
      remove :status
    end

    execute("""
    DROP TRIGGER draft_revisions_guard_truncate ON draft_revisions
    """)

    execute("""
    DROP TRIGGER draft_revisions_guard_row ON draft_revisions
    """)

    execute("""
    DROP FUNCTION draft_revisions_append_only()
    """)

    drop_if_exists constraint(:draft_revisions, :draft_revisions_first_has_no_parent)

    drop_if_exists constraint(:draft_revisions, :draft_revisions_provenance)

    drop_if_exists constraint(:draft_revisions, :draft_revisions_content_sha256_length)

    drop_if_exists constraint(:draft_revisions, :draft_revisions_trace_ids)

    drop constraint(:draft_revisions, "draft_revisions_model_invocation_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_decision_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_agent_run_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_author_user_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_ai_baseline_revision_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_parent_revision_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_draft_id_fkey")

    drop constraint(:draft_revisions, "draft_revisions_tenant_id_fkey")

    alter table(:draft_revisions) do
      modify :draft_id, :uuid
    end

    execute("""
    DROP TRIGGER approvals_guard_truncate ON approvals
    """)

    execute("""
    DROP TRIGGER approvals_guard_row ON approvals
    """)

    execute("""
    DROP FUNCTION approvals_terminal_immutable()
    """)

    drop_if_exists constraint(:approvals, :approvals_invalidated_reason)

    drop_if_exists constraint(:approvals, :approvals_revision_sha256_length)

    drop_if_exists constraint(:approvals, :approvals_verdict_status)

    drop_if_exists constraint(:approvals, :approvals_status)

    drop_if_exists constraint(:approvals, :approvals_trace_ids)

    drop constraint(:approvals, "approvals_revoked_by_id_fkey")

    drop constraint(:approvals, "approvals_approver_id_fkey")

    drop constraint(:approvals, "approvals_campaign_id_fkey")

    drop constraint(:approvals, "approvals_recipient_contact_id_fkey")

    drop constraint(:approvals, "approvals_draft_revision_id_fkey")

    drop constraint(:approvals, "approvals_draft_id_fkey")

    drop constraint(:approvals, "approvals_tenant_id_fkey")

    drop_if_exists unique_index(:approvals, [:draft_id],
                     name: "approvals_one_live_per_draft_index"
                   )

    alter table(:approvals) do
      modify :draft_id, :uuid
    end

    drop table(:drafts)

    execute("""
    DROP TRIGGER suppressions_guard_truncate ON suppressions
    """)

    execute("""
    DROP TRIGGER suppressions_guard_row ON suppressions
    """)

    execute("""
    DROP FUNCTION suppressions_append_only()
    """)

    drop_if_exists constraint(:suppressions, :suppressions_bounce_source)

    drop_if_exists constraint(:suppressions, :suppressions_reply_source)

    drop_if_exists constraint(:suppressions, :suppressions_value_normalised)

    drop_if_exists constraint(:suppressions, :suppressions_reason)

    drop_if_exists constraint(:suppressions, :suppressions_scope)

    drop_if_exists constraint(:suppressions, :suppressions_trace_ids)

    drop constraint(:suppressions, "suppressions_decision_id_fkey")

    drop constraint(:suppressions, "suppressions_created_by_user_id_fkey")

    drop constraint(:suppressions, "suppressions_tenant_id_fkey")

    alter table(:suppressions) do
      remove :decision_id
      remove :created_by_user_id
    end

    drop_if_exists unique_index(:suppressions, [:tenant_id, :scope, :value],
                     name: "suppressions_unique_value_index"
                   )

    drop table(:suppressions)

    alter table(:draft_revisions) do
      remove :model_invocation_id
      remove :decision_id
      remove :agent_run_id
      remove :author_user_id
      remove :ai_baseline_revision_id
      remove :parent_revision_id
    end

    drop_if_exists unique_index(:draft_revisions, [:draft_id, :revision_number],
                     name: "draft_revisions_unique_number_index"
                   )

    alter table(:draft_revisions) do
      remove :draft_id
      remove :tenant_id
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :diff_from_ai_baseline
      remove :diff_from_parent
      remove :canonicalization_version
      remove :content_sha256
      remove :risk_flags
      remove :cta
      remove :angle
      remove :body_text
      remove :subject
      remove :author_type
      remove :revision_number
    end

    execute("""
    DROP TRIGGER revision_citations_guard_truncate ON revision_citations
    """)

    execute("""
    DROP TRIGGER revision_citations_guard_row ON revision_citations
    """)

    execute("""
    DROP FUNCTION revision_citations_append_only()
    """)

    drop_if_exists constraint(:revision_citations, :revision_citations_kind)

    drop_if_exists constraint(:revision_citations, :revision_citations_trace_ids)

    drop constraint(:revision_citations, "revision_citations_evidence_claim_id_fkey")

    drop constraint(:revision_citations, "revision_citations_draft_revision_id_fkey")

    drop constraint(:revision_citations, "revision_citations_tenant_id_fkey")

    alter table(:revision_citations) do
      modify :draft_revision_id, :uuid
    end

    alter table(:approvals) do
      modify :draft_revision_id, :uuid
    end

    drop table(:draft_revisions)

    drop_if_exists unique_index(
                     :revision_citations,
                     [:draft_revision_id, :evidence_claim_id, :kind, :text],
                     name: "revision_citations_unique_citation_index"
                   )

    drop table(:revision_citations)

    drop table(:approvals)

    execute(
      "ALTER TABLE drafts ALTER CONSTRAINT drafts_current_revision_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end
end
