defmodule SdrAgent.Repo.Migrations.S12bWireWitness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wire_witness_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :proxy_record_ref, :text, null: false
      add :proxy_request_sha256, :binary
      add :proxy_response_sha256, :binary
      add :link_status, :text, null: false
      add :method, :text, null: false
      add :evidence, :map, null: false, default: %{}
      add :recorded_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "wire_witness_links_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :model_invocation_id,
          references(:model_invocations,
            column: :id,
            name: "wire_witness_links_model_invocation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :supersedes_id,
          references(:wire_witness_links,
            column: :id,
            name: "wire_witness_links_supersedes_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(
             :wire_witness_links,
             [:tenant_id, :model_invocation_id, :proxy_record_ref],
             name: "wire_witness_links_unique_root_index",
             where: "(supersedes_id IS NULL)"
           )

    create unique_index(:wire_witness_links, [:supersedes_id],
             name: "wire_witness_links_unique_supersedes_index",
             where: "(supersedes_id IS NOT NULL)"
           )

    create constraint(:wire_witness_links, :wire_witness_links_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:wire_witness_links, :wire_witness_links_link_status,
             check: """
               link_status IN ('inferred', 'reconciled', 'mismatch')
             """
           )

    create constraint(:wire_witness_links, :wire_witness_links_method,
             check: """
               method IN ('time_window', 'propagated_id')
             """
           )

    create constraint(:wire_witness_links, :wire_witness_links_record_ref,
             check: """
               proxy_record_ref ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
             """
           )

    create constraint(:wire_witness_links, :wire_witness_links_digests,
             check: """
               (proxy_request_sha256 IS NULL OR octet_length(proxy_request_sha256) = 32) AND (proxy_response_sha256 IS NULL OR octet_length(proxy_response_sha256) = 32)
             """
           )

    create constraint(:wire_witness_links, :wire_witness_links_evidence_object,
             check: """
               jsonb_typeof(evidence) = 'object' AND octet_length(evidence::text) <= 8192
             """
           )

    execute("""
    CREATE FUNCTION wire_witness_links_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER wire_witness_links_guard_row BEFORE UPDATE OR DELETE ON wire_witness_links FOR EACH ROW EXECUTE FUNCTION wire_witness_links_append_only()
    """)

    execute("""
    CREATE TRIGGER wire_witness_links_guard_truncate BEFORE TRUNCATE ON wire_witness_links FOR EACH STATEMENT EXECUTE FUNCTION wire_witness_links_append_only()
    """)

    execute("""
    CREATE UNIQUE INDEX wire_witness_links_subject_id_index ON wire_witness_links (tenant_id, model_invocation_id, proxy_record_ref, id)
    """)

    execute("""
    ALTER TABLE wire_witness_links ADD CONSTRAINT wire_witness_links_same_subject_fkey FOREIGN KEY (tenant_id, model_invocation_id, proxy_record_ref, supersedes_id) REFERENCES wire_witness_links (tenant_id, model_invocation_id, proxy_record_ref, id) ON DELETE RESTRICT
    """)

    execute("""
    CREATE FUNCTION wire_witness_links_mismatch_lineage() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
      previous wire_witness_links%ROWTYPE;
    BEGIN
      IF NEW.supersedes_id IS NULL THEN
        RETURN NEW;
      END IF;
      SELECT * INTO previous FROM wire_witness_links WHERE id = NEW.supersedes_id;
      IF previous.link_status = 'mismatch' AND
         (NEW.evidence ->> 'projection_version') IS NOT DISTINCT FROM
         (previous.evidence ->> 'projection_version') THEN
        RAISE EXCEPTION 'wire witness mismatch % can only be superseded under a different projection version', previous.id
          USING ERRCODE = 'check_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER wire_witness_links_mismatch_lineage BEFORE INSERT ON wire_witness_links FOR EACH ROW EXECUTE FUNCTION wire_witness_links_mismatch_lineage()
    """)
  end

  def down do
    execute("""
    DROP TRIGGER wire_witness_links_mismatch_lineage ON wire_witness_links
    """)

    execute("""
    DROP FUNCTION wire_witness_links_mismatch_lineage()
    """)

    execute("""
    ALTER TABLE wire_witness_links DROP CONSTRAINT wire_witness_links_same_subject_fkey
    """)

    execute("""
    DROP INDEX wire_witness_links_subject_id_index
    """)

    execute("""
    DROP TRIGGER wire_witness_links_guard_truncate ON wire_witness_links
    """)

    execute("""
    DROP TRIGGER wire_witness_links_guard_row ON wire_witness_links
    """)

    execute("""
    DROP FUNCTION wire_witness_links_append_only()
    """)

    drop_if_exists constraint(:wire_witness_links, :wire_witness_links_evidence_object)

    drop_if_exists constraint(:wire_witness_links, :wire_witness_links_digests)

    drop_if_exists constraint(:wire_witness_links, :wire_witness_links_record_ref)

    drop_if_exists constraint(:wire_witness_links, :wire_witness_links_method)

    drop_if_exists constraint(:wire_witness_links, :wire_witness_links_link_status)

    drop_if_exists constraint(:wire_witness_links, :wire_witness_links_trace_ids)

    drop constraint(:wire_witness_links, "wire_witness_links_supersedes_id_fkey")

    drop constraint(:wire_witness_links, "wire_witness_links_model_invocation_id_fkey")

    drop constraint(:wire_witness_links, "wire_witness_links_tenant_id_fkey")

    drop_if_exists unique_index(:wire_witness_links, [:supersedes_id],
                     name: "wire_witness_links_unique_supersedes_index"
                   )

    drop_if_exists unique_index(
                     :wire_witness_links,
                     [:tenant_id, :model_invocation_id, :proxy_record_ref],
                     name: "wire_witness_links_unique_root_index"
                   )

    drop table(:wire_witness_links)
  end
end
