defmodule SdrAgent.Repo.Migrations.S7Operations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:failures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:agent_runs) do
      modify :attention_failure_id,
             references(:failures,
               column: :id,
               name: "agent_runs_attention_failure_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:failures) do
      add :subject_resource, :text, null: false
      add :subject_id, :uuid, null: false
      add :class, :text, null: false
      add :severity, :text, null: false
      add :message, :text, null: false
      add :detail_sha256, :binary
      add :retryable, :boolean, null: false, default: true
      add :status, :text, null: false, default: "open"
      add :acknowledged_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec
      add :resolved_by_type, :text
      add :resolution_note, :text
      add :occurred_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "failures_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :operation_id, :uuid

      add :resolved_by_id,
          references(:users,
            column: :id,
            name: "failures_resolved_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:agent_runs) do
      modify :operation_id,
             references(:operations,
               column: :id,
               name: "agent_runs_operation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:failures) do
      modify :operation_id,
             references(:operations,
               column: :id,
               name: "failures_operation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:failures, :failures_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:failures, :failures_status,
             check: """
               status IN ('open', 'acknowledged', 'resolved')
             """
           )

    create constraint(:failures, :failures_resolution_note_when_resolved,
             check: """
               status <> 'resolved' OR resolution_note IS NOT NULL
             """
           )

    execute("""
    ALTER TABLE failures ADD CONSTRAINT failures_detail_sha256_payload_fkey FOREIGN KEY (tenant_id, detail_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    alter table(:operations) do
      add :kind, :text, null: false
      add :queue, :text, null: false
      add :oban_job_id, :bigint
      add :subject_resource, :text, null: false
      add :subject_id, :uuid, null: false
      add :idempotency_key, :text, null: false
      add :correlation_id, :uuid, null: false
      add :status, :text, null: false, default: "enqueued"
      add :attempts, :bigint, null: false, default: 0
      add :max_attempts, :bigint, null: false, default: 1
      add :scheduled_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "operations_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:operations, [:tenant_id, :idempotency_key],
             name: "operations_unique_idempotency_key_index"
           )

    alter table(:operations) do
      add :last_failure_id,
          references(:failures,
            column: :id,
            name: "operations_last_failure_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:operations, :operations_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:operations, :operations_status,
             check: """
               status IN ('enqueued', 'running', 'succeeded', 'failed', 'cancelled', 'discarded')
             """
           )

    create constraint(:operations, :operations_attempts_bounded,
             check: """
               attempts >= 0 AND attempts <= max_attempts
             """
           )
  end

  def down do
    drop_if_exists constraint(:operations, :operations_attempts_bounded)

    drop_if_exists constraint(:operations, :operations_status)

    drop_if_exists constraint(:operations, :operations_trace_ids)

    drop constraint(:operations, "operations_last_failure_id_fkey")

    drop constraint(:operations, "operations_tenant_id_fkey")

    alter table(:operations) do
      remove :last_failure_id
    end

    drop_if_exists unique_index(:operations, [:tenant_id, :idempotency_key],
                     name: "operations_unique_idempotency_key_index"
                   )

    alter table(:operations) do
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :finished_at
      remove :started_at
      remove :scheduled_at
      remove :max_attempts
      remove :attempts
      remove :status
      remove :correlation_id
      remove :idempotency_key
      remove :subject_id
      remove :subject_resource
      remove :oban_job_id
      remove :queue
      remove :kind
    end

    execute("""
    ALTER TABLE failures DROP CONSTRAINT failures_detail_sha256_payload_fkey
    """)

    drop_if_exists constraint(:failures, :failures_resolution_note_when_resolved)

    drop_if_exists constraint(:failures, :failures_status)

    drop_if_exists constraint(:failures, :failures_trace_ids)

    drop constraint(:failures, "failures_resolved_by_id_fkey")

    drop constraint(:failures, "failures_operation_id_fkey")

    drop constraint(:failures, "failures_tenant_id_fkey")

    alter table(:failures) do
      modify :operation_id, :uuid
    end

    drop constraint(:agent_runs, "agent_runs_attention_failure_id_fkey")

    drop constraint(:agent_runs, "agent_runs_operation_id_fkey")

    alter table(:agent_runs) do
      modify :operation_id, :uuid
    end

    drop table(:operations)

    alter table(:failures) do
      remove :resolved_by_id
      remove :operation_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :occurred_at
      remove :resolution_note
      remove :resolved_by_type
      remove :resolved_at
      remove :acknowledged_at
      remove :status
      remove :retryable
      remove :detail_sha256
      remove :message
      remove :severity
      remove :class
      remove :subject_id
      remove :subject_resource
    end

    alter table(:agent_runs) do
      modify :attention_failure_id, :uuid
    end

    drop table(:failures)
  end
end
