defmodule SdrAgent.Repo.Migrations.S9bReplyAssessments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reply_assessments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :classification, :text, null: false
      add :sentiment, :text, null: false
      add :intent, :text
      add :suggested_next_action, :text, null: false
      add :confidence, :float, null: false
      add :source, :text, null: false
      add :reason, :text
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "reply_assessments_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :reply_id,
          references(:replies,
            column: :id,
            name: "reply_assessments_reply_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "reply_assessments_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :decision_id,
          references(:decisions,
            column: :id,
            name: "reply_assessments_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :model_invocation_id,
          references(:model_invocations,
            column: :id,
            name: "reply_assessments_model_invocation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :reviewer_user_id,
          references(:users,
            column: :id,
            name: "reply_assessments_reviewer_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :supersedes_id,
          references(:reply_assessments,
            column: :id,
            name: "reply_assessments_supersedes_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:reply_assessments, [:reply_id],
             name: "reply_assessments_unique_root_index",
             where: "(supersedes_id IS NULL)"
           )

    create unique_index(:reply_assessments, [:supersedes_id],
             name: "reply_assessments_unique_supersedes_index",
             where: "(supersedes_id IS NOT NULL)"
           )

    create constraint(:reply_assessments, :reply_assessments_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:reply_assessments, :reply_assessments_classification,
             check: """
               classification IN ('interested', 'objection', 'referral', 'not_now', 'unsubscribe', 'out_of_office', 'irrelevant', 'unknown')
             """
           )

    create constraint(:reply_assessments, :reply_assessments_sentiment,
             check: """
               sentiment IN ('positive', 'neutral', 'negative')
             """
           )

    create constraint(:reply_assessments, :reply_assessments_next_action,
             check: """
               suggested_next_action IN ('hand_off', 'nurture', 'stop', 'escalate', 'none')
             """
           )

    create constraint(:reply_assessments, :reply_assessments_confidence_range,
             check: """
               confidence >= 0 AND confidence <= 1
             """
           )

    create constraint(:reply_assessments, :reply_assessments_source_provenance,
             check: """
               (source = 'agent' AND agent_run_id IS NOT NULL AND decision_id IS NOT NULL AND model_invocation_id IS NOT NULL) OR (source = 'human_override' AND reviewer_user_id IS NOT NULL AND reason IS NOT NULL AND supersedes_id IS NOT NULL)
             """
           )

    execute("""
    CREATE FUNCTION reply_assessments_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER reply_assessments_guard_row BEFORE UPDATE OR DELETE ON reply_assessments FOR EACH ROW EXECUTE FUNCTION reply_assessments_append_only()
    """)

    execute("""
    CREATE TRIGGER reply_assessments_guard_truncate BEFORE TRUNCATE ON reply_assessments FOR EACH STATEMENT EXECUTE FUNCTION reply_assessments_append_only()
    """)
  end

  def down do
    execute("""
    DROP TRIGGER reply_assessments_guard_truncate ON reply_assessments
    """)

    execute("""
    DROP TRIGGER reply_assessments_guard_row ON reply_assessments
    """)

    execute("""
    DROP FUNCTION reply_assessments_append_only()
    """)

    drop_if_exists constraint(:reply_assessments, :reply_assessments_source_provenance)

    drop_if_exists constraint(:reply_assessments, :reply_assessments_confidence_range)

    drop_if_exists constraint(:reply_assessments, :reply_assessments_next_action)

    drop_if_exists constraint(:reply_assessments, :reply_assessments_sentiment)

    drop_if_exists constraint(:reply_assessments, :reply_assessments_classification)

    drop_if_exists constraint(:reply_assessments, :reply_assessments_trace_ids)

    drop constraint(:reply_assessments, "reply_assessments_supersedes_id_fkey")

    drop constraint(:reply_assessments, "reply_assessments_reviewer_user_id_fkey")

    drop constraint(:reply_assessments, "reply_assessments_model_invocation_id_fkey")

    drop constraint(:reply_assessments, "reply_assessments_decision_id_fkey")

    drop constraint(:reply_assessments, "reply_assessments_agent_run_id_fkey")

    drop constraint(:reply_assessments, "reply_assessments_reply_id_fkey")

    drop constraint(:reply_assessments, "reply_assessments_tenant_id_fkey")

    drop_if_exists unique_index(:reply_assessments, [:supersedes_id],
                     name: "reply_assessments_unique_supersedes_index"
                   )

    drop_if_exists unique_index(:reply_assessments, [:reply_id],
                     name: "reply_assessments_unique_root_index"
                   )

    drop table(:reply_assessments)
  end
end
