defmodule SdrAgent.Repo.Migrations.S5Domain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :name, :text, null: false
      add :domain, :citext, null: false
      add :website_url, :text
      add :industry, :text
      add :employee_count, :bigint
      add :geography, :text
      add :crm_provider, :text
      add :crm_external_id, :text
      add :source, :text, null: false
      add :status, :text, null: false, default: "active"
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "accounts_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:accounts, [:tenant_id, :domain], name: "accounts_unique_domain_index")

    create unique_index(:accounts, [:tenant_id, :crm_provider, :crm_external_id],
             name: "accounts_unique_crm_id_index",
             where: "(crm_external_id IS NOT NULL)"
           )

    create constraint(:accounts, :accounts_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:accounts, :accounts_status,
             check: """
               status IN ('active', 'archived')
             """
           )

    create table(:campaign_enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :current_step_position, :bigint, null: false, default: 0
      add :next_step_due_at, :utc_datetime_usec
      add :status, :text, null: false, default: "active"
      add :stop_reason, :text
      add :enrolled_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "campaign_enrollments_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :campaign_id, :uuid, null: false
      add :lead_id, :uuid, null: false
    end

    create unique_index(:campaign_enrollments, [:campaign_id, :lead_id],
             name: "campaign_enrollments_unique_campaign_lead_index"
           )

    create table(:campaigns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:campaign_enrollments) do
      modify :campaign_id,
             references(:campaigns,
               column: :id,
               name: "campaign_enrollments_campaign_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:campaigns) do
      add :name, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :sender_name, :text, null: false, default: "Demo SDR"
      add :sender_email, :citext, null: false, default: "sdr@example.test"
      add :timezone, :text, null: false, default: "America/Denver"
      add :quiet_hours_start, :time, null: false, default: fragment("'18:00:00'")
      add :quiet_hours_end, :time, null: false, default: fragment("'08:00:00'")
      add :autonomy_tier, :bigint, null: false, default: 0
      add :footer_template_version, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "campaigns_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :icp_definition_id, :uuid, null: false
      add :sequence_id, :uuid
    end

    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :citext, null: false
      add :title, :text
      add :persona, :text
      add :timezone, :text
      add :crm_external_id, :text
      add :status, :text, null: false, default: "active"
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "contacts_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:contacts, [:tenant_id, :email], name: "contacts_unique_email_index")

    alter table(:contacts) do
      add :account_id,
          references(:accounts,
            column: :id,
            name: "contacts_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(:contacts, :contacts_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:contacts, :contacts_status,
             check: """
               status IN ('active', 'archived')
             """
           )

    create table(:evidence_claims, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :claim, :text, null: false
      add :quote, :text, null: false
      add :source_location, :map, null: false
      add :confidence, :float, null: false
      add :quality, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "evidence_claims_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :research_artifact_id, :uuid, null: false
      add :lead_id, :uuid, null: false

      add :extraction_decision_id,
          references(:decisions,
            column: :id,
            name: "evidence_claims_extraction_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :model_invocation_id,
          references(:model_invocations,
            column: :id,
            name: "evidence_claims_model_invocation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:icp_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:campaigns) do
      modify :icp_definition_id,
             references(:icp_definitions,
               column: :id,
               name: "campaigns_icp_definition_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:icp_definitions) do
      add :name, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"
      add :description, :text
      add :criteria, :map, null: false
      add :criteria_sha256, :binary, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "icp_definitions_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:icp_definitions, [:tenant_id, :name, :version],
             name: "icp_definitions_unique_name_version_index"
           )

    create constraint(:icp_definitions, :icp_definitions_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:icp_definitions, :icp_definitions_status,
             check: """
               status IN ('draft', 'active', 'retired')
             """
           )

    create constraint(:icp_definitions, :icp_definitions_version_positive,
             check: """
               version >= 1
             """
           )

    create constraint(:icp_definitions, :icp_definitions_criteria_sha256_length,
             check: """
               octet_length(criteria_sha256) = 32
             """
           )

    create table(:leads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:campaign_enrollments) do
      modify :lead_id,
             references(:leads,
               column: :id,
               name: "campaign_enrollments_lead_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:campaign_enrollments, :campaign_enrollments_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:campaign_enrollments, :campaign_enrollments_status,
             check: """
               status IN ('active', 'paused', 'replied', 'completed', 'stopped')
             """
           )

    create constraint(:campaign_enrollments, :campaign_enrollments_stop_reason_when_stopped,
             check: """
               status <> 'stopped' OR stop_reason IS NOT NULL
             """
           )

    alter table(:evidence_claims) do
      modify :lead_id,
             references(:leads,
               column: :id,
               name: "evidence_claims_lead_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:leads) do
      add :source, :text, null: false
      add :status, :text, null: false, default: "new"
      add :status_reason, :text
      add :assigned_at, :utc_datetime_usec
      add :handed_off_at, :utc_datetime_usec
      add :closed_at, :utc_datetime_usec
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "leads_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :contact_id,
          references(:contacts,
            column: :id,
            name: "leads_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "leads_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "leads_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :last_decision_id,
          references(:decisions,
            column: :id,
            name: "leads_last_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:leads, [:tenant_id, :contact_id],
             name: "leads_unique_open_lead_index",
             where: "(status NOT IN ('disqualified', 'converted', 'nurture', 'stopped'))"
           )

    create constraint(:leads, :leads_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:leads, :leads_status,
             check: """
               status IN ('new', 'assigned', 'researching', 'qualifying', 'qualified', 'disqualified', 'in_outreach', 'replied', 'converted', 'nurture', 'stopped', 'blocked')
             """
           )

    create constraint(:leads, :leads_reason_when_stopped_or_blocked,
             check: """
               status NOT IN ('stopped', 'blocked') OR status_reason IS NOT NULL
             """
           )

    create table(:qualification_evidences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "qualification_evidences_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :qualification_id, :uuid, null: false

      add :evidence_claim_id,
          references(:evidence_claims,
            column: :id,
            name: "qualification_evidences_evidence_claim_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:qualification_evidences, [:qualification_id, :evidence_claim_id],
             name: "qualification_evidences_unique_citation_index"
           )

    create table(:qualifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:qualification_evidences) do
      modify :qualification_id,
             references(:qualifications,
               column: :id,
               name: "qualification_evidences_qualification_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:qualification_evidences, :qualification_evidences_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION qualification_evidences_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER qualification_evidences_guard_row BEFORE UPDATE OR DELETE ON qualification_evidences FOR EACH ROW EXECUTE FUNCTION qualification_evidences_append_only()
    """)

    execute("""
    CREATE TRIGGER qualification_evidences_guard_truncate BEFORE TRUNCATE ON qualification_evidences FOR EACH STATEMENT EXECUTE FUNCTION qualification_evidences_append_only()
    """)

    alter table(:qualifications) do
      add :source, :text, null: false
      add :qualified, :boolean, null: false
      add :score, :bigint, null: false
      add :criteria, :map, null: false
      add :confidence, :float, null: false
      add :reason, :text, null: false
      add :output_schema_version, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "qualifications_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :lead_id,
          references(:leads,
            column: :id,
            name: "qualifications_lead_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :icp_definition_id,
          references(:icp_definitions,
            column: :id,
            name: "qualifications_icp_definition_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "qualifications_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :decision_id,
          references(:decisions,
            column: :id,
            name: "qualifications_decision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :supersedes_id,
          references(:qualifications,
            column: :id,
            name: "qualifications_supersedes_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :created_by_user_id,
          references(:users,
            column: :id,
            name: "qualifications_created_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:qualifications, [:lead_id],
             name: "qualifications_unique_root_index",
             where: "(supersedes_id IS NULL)"
           )

    create unique_index(:qualifications, [:supersedes_id],
             name: "qualifications_unique_supersedes_index",
             where: "(supersedes_id IS NOT NULL)"
           )

    create constraint(:qualifications, :qualifications_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:qualifications, :qualifications_score_range,
             check: """
               score >= 0 AND score <= 100
             """
           )

    create constraint(:qualifications, :qualifications_confidence_range,
             check: """
               confidence >= 0 AND confidence <= 1
             """
           )

    create constraint(:qualifications, :qualifications_source_provenance,
             check: """
               (source = 'agent' AND agent_run_id IS NOT NULL) OR (source = 'human_override' AND created_by_user_id IS NOT NULL AND supersedes_id IS NOT NULL)
             """
           )

    execute("""
    CREATE FUNCTION qualifications_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER qualifications_guard_row BEFORE UPDATE OR DELETE ON qualifications FOR EACH ROW EXECUTE FUNCTION qualifications_append_only()
    """)

    execute("""
    CREATE TRIGGER qualifications_guard_truncate BEFORE TRUNCATE ON qualifications FOR EACH STATEMENT EXECUTE FUNCTION qualifications_append_only()
    """)

    create table(:research_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:evidence_claims) do
      modify :research_artifact_id,
             references(:research_artifacts,
               column: :id,
               name: "evidence_claims_research_artifact_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:evidence_claims, :evidence_claims_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:evidence_claims, :evidence_claims_confidence_range,
             check: """
               confidence >= 0 AND confidence <= 1
             """
           )

    execute("""
    CREATE FUNCTION evidence_claims_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER evidence_claims_guard_row BEFORE UPDATE OR DELETE ON evidence_claims FOR EACH ROW EXECUTE FUNCTION evidence_claims_append_only()
    """)

    execute("""
    CREATE TRIGGER evidence_claims_guard_truncate BEFORE TRUNCATE ON evidence_claims FOR EACH STATEMENT EXECUTE FUNCTION evidence_claims_append_only()
    """)

    alter table(:research_artifacts) do
      add :source_type, :text, null: false
      add :provider, :text, null: false
      add :source_url, :text, null: false
      add :retrieved_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime_usec
      add :title, :text
      add :content_sha256, :binary, null: false
      add :excerpt, :text, null: false
      add :trust_level, :text, null: false
      add :freshness, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "research_artifacts_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :lead_id,
          references(:leads,
            column: :id,
            name: "research_artifacts_lead_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:research_artifacts, [:lead_id, :source_url, :content_sha256],
             name: "research_artifacts_unique_source_index"
           )

    alter table(:research_artifacts) do
      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "research_artifacts_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :tool_invocation_id,
          references(:tool_invocations,
            column: :id,
            name: "research_artifacts_tool_invocation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(:research_artifacts, :research_artifacts_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:research_artifacts, :research_artifacts_excerpt_length,
             check: """
               char_length(excerpt) <= 2000
             """
           )

    create constraint(:research_artifacts, :research_artifacts_content_sha256_length,
             check: """
               octet_length(content_sha256) = 32
             """
           )

    execute("""
    CREATE FUNCTION research_artifacts_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER research_artifacts_guard_row BEFORE UPDATE OR DELETE ON research_artifacts FOR EACH ROW EXECUTE FUNCTION research_artifacts_append_only()
    """)

    execute("""
    CREATE TRIGGER research_artifacts_guard_truncate BEFORE TRUNCATE ON research_artifacts FOR EACH STATEMENT EXECUTE FUNCTION research_artifacts_append_only()
    """)

    execute("""
    ALTER TABLE research_artifacts ADD CONSTRAINT research_artifacts_content_sha256_payload_fkey FOREIGN KEY (tenant_id, content_sha256) REFERENCES payloads (tenant_id, sha256) ON DELETE RESTRICT
    """)

    create table(:sequence_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :position, :bigint, null: false
      add :channel, :text, null: false
      add :delay_days, :bigint, null: false
      add :instructions, :text, null: false
      add :requires_approval, :boolean, null: false, default: true
      add :stop_on_reply, :boolean, null: false, default: true
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "sequence_steps_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :sequence_id, :uuid, null: false
    end

    create unique_index(:sequence_steps, [:sequence_id, :position],
             name: "sequence_steps_unique_position_index"
           )

    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:campaigns) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "campaigns_sequence_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:campaigns, :campaigns_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:campaigns, :campaigns_status,
             check: """
               status IN ('draft', 'active', 'paused', 'completed', 'archived')
             """
           )

    create constraint(:campaigns, :campaigns_tier_zero,
             check: """
               autonomy_tier = 0
             """
           )

    create constraint(:campaigns, :campaigns_sequence_when_live,
             check: """
               status IN ('draft', 'archived') OR sequence_id IS NOT NULL
             """
           )

    alter table(:sequence_steps) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "sequence_steps_sequence_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:sequence_steps, :sequence_steps_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:sequence_steps, :sequence_steps_first_step_immediate,
             check: """
               position <> 1 OR delay_days = 0
             """
           )

    create constraint(:sequence_steps, :sequence_steps_tier_zero,
             check: """
               requires_approval = true AND stop_on_reply = true
             """
           )

    create constraint(:sequence_steps, :sequence_steps_channel,
             check: """
               channel = 'email'
             """
           )

    alter table(:sequences) do
      add :name, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "sequences_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:sequences, [:tenant_id, :name, :version],
             name: "sequences_unique_name_version_index"
           )

    create constraint(:sequences, :sequences_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    create constraint(:sequences, :sequences_status,
             check: """
               status IN ('draft', 'active', 'retired')
             """
           )

    create constraint(:sequences, :sequences_version_positive,
             check: """
               version >= 1
             """
           )

    alter table(:users) do
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :role, :text, null: false, default: "reviewer"
      add :status, :text, null: false, default: "active"
      add :display_name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "users_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create constraint(:users, :users_role,
             check: """
               role IN ('admin', 'reviewer', 'auditor')
             """
           )

    create constraint(:users, :users_status,
             check: """
               status IN ('active', 'disabled')
             """
           )
  end

  def down do
    drop_if_exists constraint(:users, :users_status)

    drop_if_exists constraint(:users, :users_role)

    drop constraint(:users, "users_tenant_id_fkey")

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :display_name
      remove :status
      remove :role
      remove :hashed_password
      remove :email
    end

    drop_if_exists constraint(:sequences, :sequences_version_positive)

    drop_if_exists constraint(:sequences, :sequences_status)

    drop_if_exists constraint(:sequences, :sequences_trace_ids)

    drop constraint(:sequences, "sequences_tenant_id_fkey")

    drop_if_exists unique_index(:sequences, [:tenant_id, :name, :version],
                     name: "sequences_unique_name_version_index"
                   )

    alter table(:sequences) do
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :status
      remove :version
      remove :name
    end

    drop_if_exists constraint(:sequence_steps, :sequence_steps_channel)

    drop_if_exists constraint(:sequence_steps, :sequence_steps_tier_zero)

    drop_if_exists constraint(:sequence_steps, :sequence_steps_first_step_immediate)

    drop_if_exists constraint(:sequence_steps, :sequence_steps_trace_ids)

    drop constraint(:sequence_steps, "sequence_steps_sequence_id_fkey")

    drop constraint(:sequence_steps, "sequence_steps_tenant_id_fkey")

    alter table(:sequence_steps) do
      modify :sequence_id, :uuid
    end

    drop_if_exists constraint(:campaigns, :campaigns_sequence_when_live)

    drop_if_exists constraint(:campaigns, :campaigns_tier_zero)

    drop_if_exists constraint(:campaigns, :campaigns_status)

    drop_if_exists constraint(:campaigns, :campaigns_trace_ids)

    drop constraint(:campaigns, "campaigns_sequence_id_fkey")

    drop constraint(:campaigns, "campaigns_icp_definition_id_fkey")

    drop constraint(:campaigns, "campaigns_tenant_id_fkey")

    alter table(:campaigns) do
      modify :sequence_id, :uuid
    end

    drop table(:sequences)

    drop_if_exists unique_index(:sequence_steps, [:sequence_id, :position],
                     name: "sequence_steps_unique_position_index"
                   )

    drop table(:sequence_steps)

    execute("""
    ALTER TABLE research_artifacts DROP CONSTRAINT research_artifacts_content_sha256_payload_fkey
    """)

    execute("""
    DROP TRIGGER research_artifacts_guard_truncate ON research_artifacts
    """)

    execute("""
    DROP TRIGGER research_artifacts_guard_row ON research_artifacts
    """)

    execute("""
    DROP FUNCTION research_artifacts_append_only()
    """)

    drop_if_exists constraint(:research_artifacts, :research_artifacts_content_sha256_length)

    drop_if_exists constraint(:research_artifacts, :research_artifacts_excerpt_length)

    drop_if_exists constraint(:research_artifacts, :research_artifacts_trace_ids)

    drop constraint(:research_artifacts, "research_artifacts_tool_invocation_id_fkey")

    drop constraint(:research_artifacts, "research_artifacts_agent_run_id_fkey")

    drop constraint(:research_artifacts, "research_artifacts_lead_id_fkey")

    drop constraint(:research_artifacts, "research_artifacts_tenant_id_fkey")

    alter table(:research_artifacts) do
      remove :tool_invocation_id
      remove :agent_run_id
    end

    drop_if_exists unique_index(:research_artifacts, [:lead_id, :source_url, :content_sha256],
                     name: "research_artifacts_unique_source_index"
                   )

    alter table(:research_artifacts) do
      remove :lead_id
      remove :tenant_id
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :metadata
      remove :freshness
      remove :trust_level
      remove :excerpt
      remove :content_sha256
      remove :title
      remove :published_at
      remove :retrieved_at
      remove :source_url
      remove :provider
      remove :source_type
    end

    execute("""
    DROP TRIGGER evidence_claims_guard_truncate ON evidence_claims
    """)

    execute("""
    DROP TRIGGER evidence_claims_guard_row ON evidence_claims
    """)

    execute("""
    DROP FUNCTION evidence_claims_append_only()
    """)

    drop_if_exists constraint(:evidence_claims, :evidence_claims_confidence_range)

    drop_if_exists constraint(:evidence_claims, :evidence_claims_trace_ids)

    drop constraint(:evidence_claims, "evidence_claims_model_invocation_id_fkey")

    drop constraint(:evidence_claims, "evidence_claims_extraction_decision_id_fkey")

    drop constraint(:evidence_claims, "evidence_claims_lead_id_fkey")

    drop constraint(:evidence_claims, "evidence_claims_research_artifact_id_fkey")

    drop constraint(:evidence_claims, "evidence_claims_tenant_id_fkey")

    alter table(:evidence_claims) do
      modify :research_artifact_id, :uuid
    end

    drop table(:research_artifacts)

    execute("""
    DROP TRIGGER qualifications_guard_truncate ON qualifications
    """)

    execute("""
    DROP TRIGGER qualifications_guard_row ON qualifications
    """)

    execute("""
    DROP FUNCTION qualifications_append_only()
    """)

    drop_if_exists constraint(:qualifications, :qualifications_source_provenance)

    drop_if_exists constraint(:qualifications, :qualifications_confidence_range)

    drop_if_exists constraint(:qualifications, :qualifications_score_range)

    drop_if_exists constraint(:qualifications, :qualifications_trace_ids)

    drop constraint(:qualifications, "qualifications_created_by_user_id_fkey")

    drop constraint(:qualifications, "qualifications_supersedes_id_fkey")

    drop constraint(:qualifications, "qualifications_decision_id_fkey")

    drop constraint(:qualifications, "qualifications_agent_run_id_fkey")

    drop constraint(:qualifications, "qualifications_icp_definition_id_fkey")

    drop constraint(:qualifications, "qualifications_lead_id_fkey")

    drop constraint(:qualifications, "qualifications_tenant_id_fkey")

    drop_if_exists unique_index(:qualifications, [:supersedes_id],
                     name: "qualifications_unique_supersedes_index"
                   )

    drop_if_exists unique_index(:qualifications, [:lead_id],
                     name: "qualifications_unique_root_index"
                   )

    alter table(:qualifications) do
      remove :created_by_user_id
      remove :supersedes_id
      remove :decision_id
      remove :agent_run_id
      remove :icp_definition_id
      remove :lead_id
      remove :tenant_id
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :output_schema_version
      remove :reason
      remove :confidence
      remove :criteria
      remove :score
      remove :qualified
      remove :source
    end

    execute("""
    DROP TRIGGER qualification_evidences_guard_truncate ON qualification_evidences
    """)

    execute("""
    DROP TRIGGER qualification_evidences_guard_row ON qualification_evidences
    """)

    execute("""
    DROP FUNCTION qualification_evidences_append_only()
    """)

    drop_if_exists constraint(:qualification_evidences, :qualification_evidences_trace_ids)

    drop constraint(:qualification_evidences, "qualification_evidences_evidence_claim_id_fkey")

    drop constraint(:qualification_evidences, "qualification_evidences_qualification_id_fkey")

    drop constraint(:qualification_evidences, "qualification_evidences_tenant_id_fkey")

    alter table(:qualification_evidences) do
      modify :qualification_id, :uuid
    end

    drop table(:qualifications)

    drop_if_exists unique_index(:qualification_evidences, [:qualification_id, :evidence_claim_id],
                     name: "qualification_evidences_unique_citation_index"
                   )

    drop table(:qualification_evidences)

    drop_if_exists constraint(:leads, :leads_reason_when_stopped_or_blocked)

    drop_if_exists constraint(:leads, :leads_status)

    drop_if_exists constraint(:leads, :leads_trace_ids)

    drop constraint(:leads, "leads_last_decision_id_fkey")

    drop constraint(:leads, "leads_owner_user_id_fkey")

    drop constraint(:leads, "leads_account_id_fkey")

    drop constraint(:leads, "leads_contact_id_fkey")

    drop constraint(:leads, "leads_tenant_id_fkey")

    drop_if_exists unique_index(:leads, [:tenant_id, :contact_id],
                     name: "leads_unique_open_lead_index"
                   )

    alter table(:leads) do
      remove :last_decision_id
      remove :owner_user_id
      remove :account_id
      remove :contact_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :closed_at
      remove :handed_off_at
      remove :assigned_at
      remove :status_reason
      remove :status
      remove :source
    end

    alter table(:evidence_claims) do
      modify :lead_id, :uuid
    end

    drop_if_exists constraint(
                     :campaign_enrollments,
                     :campaign_enrollments_stop_reason_when_stopped
                   )

    drop_if_exists constraint(:campaign_enrollments, :campaign_enrollments_status)

    drop_if_exists constraint(:campaign_enrollments, :campaign_enrollments_trace_ids)

    drop constraint(:campaign_enrollments, "campaign_enrollments_lead_id_fkey")

    drop constraint(:campaign_enrollments, "campaign_enrollments_campaign_id_fkey")

    drop constraint(:campaign_enrollments, "campaign_enrollments_tenant_id_fkey")

    alter table(:campaign_enrollments) do
      modify :lead_id, :uuid
    end

    drop table(:leads)

    drop_if_exists constraint(:icp_definitions, :icp_definitions_criteria_sha256_length)

    drop_if_exists constraint(:icp_definitions, :icp_definitions_version_positive)

    drop_if_exists constraint(:icp_definitions, :icp_definitions_status)

    drop_if_exists constraint(:icp_definitions, :icp_definitions_trace_ids)

    drop constraint(:icp_definitions, "icp_definitions_tenant_id_fkey")

    drop_if_exists unique_index(:icp_definitions, [:tenant_id, :name, :version],
                     name: "icp_definitions_unique_name_version_index"
                   )

    alter table(:icp_definitions) do
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :criteria_sha256
      remove :criteria
      remove :description
      remove :status
      remove :version
      remove :name
    end

    alter table(:campaigns) do
      modify :icp_definition_id, :uuid
    end

    drop table(:icp_definitions)

    drop table(:evidence_claims)

    drop_if_exists constraint(:contacts, :contacts_status)

    drop_if_exists constraint(:contacts, :contacts_trace_ids)

    drop constraint(:contacts, "contacts_account_id_fkey")

    drop constraint(:contacts, "contacts_tenant_id_fkey")

    alter table(:contacts) do
      remove :account_id
    end

    drop_if_exists unique_index(:contacts, [:tenant_id, :email],
                     name: "contacts_unique_email_index"
                   )

    drop table(:contacts)

    alter table(:campaigns) do
      remove :sequence_id
      remove :icp_definition_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :footer_template_version
      remove :autonomy_tier
      remove :quiet_hours_end
      remove :quiet_hours_start
      remove :timezone
      remove :sender_email
      remove :sender_name
      remove :status
      remove :name
    end

    alter table(:campaign_enrollments) do
      modify :campaign_id, :uuid
    end

    drop table(:campaigns)

    drop_if_exists unique_index(:campaign_enrollments, [:campaign_id, :lead_id],
                     name: "campaign_enrollments_unique_campaign_lead_index"
                   )

    drop table(:campaign_enrollments)

    drop_if_exists constraint(:accounts, :accounts_status)

    drop_if_exists constraint(:accounts, :accounts_trace_ids)

    drop constraint(:accounts, "accounts_tenant_id_fkey")

    drop_if_exists unique_index(:accounts, [:tenant_id, :crm_provider, :crm_external_id],
                     name: "accounts_unique_crm_id_index"
                   )

    drop_if_exists unique_index(:accounts, [:tenant_id, :domain],
                     name: "accounts_unique_domain_index"
                   )

    drop table(:accounts)
  end
end
