defmodule SdrAgent.Repo.Migrations.S11AnchoringExport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:anchor_sink_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :sink, :text, null: false
      add :status, :text, null: false
      add :receipt, :map, null: false
      add :recorded_at, :utc_datetime_usec, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "anchor_sink_receipts_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :anchor_id, :uuid, null: false
    end

    create table(:audit_anchors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:anchor_sink_receipts) do
      modify :anchor_id,
             references(:audit_anchors,
               column: :id,
               name: "anchor_sink_receipts_anchor_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:anchor_sink_receipts, :anchor_sink_receipts_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION anchor_sink_receipts_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER anchor_sink_receipts_guard_row BEFORE UPDATE OR DELETE ON anchor_sink_receipts FOR EACH ROW EXECUTE FUNCTION anchor_sink_receipts_append_only()
    """)

    execute("""
    CREATE TRIGGER anchor_sink_receipts_guard_truncate BEFORE TRUNCATE ON anchor_sink_receipts FOR EACH STATEMENT EXECUTE FUNCTION anchor_sink_receipts_append_only()
    """)

    alter table(:audit_anchors) do
      add :anchor_number, :bigint, null: false
      add :from_sequence, :bigint, null: false
      add :to_sequence, :bigint, null: false
      add :head_event_hash, :binary, null: false
      add :prior_anchor_hash, :binary
      add :statement_bytes, :binary, null: false
      add :anchor_hash, :binary, null: false
      add :signature, :binary, null: false
      add :key_id, :text, null: false
      add :key_status_at_signing, :text, null: false
      add :canonicalization_version, :text, null: false
      add :sdr_agent_git_sha, :text, null: false
      add :trigger, :text, null: false
      add :trace_id, :text, null: false
      add :span_id, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "audit_anchors_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:audit_anchors, [:tenant_id, :to_sequence],
             name: "audit_anchors_unique_head_index"
           )

    create unique_index(:audit_anchors, [:tenant_id, :anchor_number],
             name: "audit_anchors_unique_number_index"
           )

    alter table(:audit_anchors) do
      add :prior_anchor_id,
          references(:audit_anchors,
            column: :id,
            name: "audit_anchors_prior_anchor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:audit_anchors, :audit_anchors_valid_range,
             check: """
               to_sequence >= from_sequence
             """
           )

    create constraint(:audit_anchors, :audit_anchors_hash_lengths,
             check: """
               octet_length(head_event_hash) = 32 AND octet_length(anchor_hash) = 32 AND (prior_anchor_hash IS NULL OR octet_length(prior_anchor_hash) = 32)
             """
           )

    create constraint(:audit_anchors, :audit_anchors_signature_length,
             check: """
               octet_length(signature) = 64
             """
           )

    create constraint(:audit_anchors, :audit_anchors_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION audit_anchors_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER audit_anchors_guard_row BEFORE UPDATE OR DELETE ON audit_anchors FOR EACH ROW EXECUTE FUNCTION audit_anchors_append_only()
    """)

    execute("""
    CREATE TRIGGER audit_anchors_guard_truncate BEFORE TRUNCATE ON audit_anchors FOR EACH STATEMENT EXECUTE FUNCTION audit_anchors_append_only()
    """)

    create table(:audit_exports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :requested_by_type, :text, null: false
      add :requested_by_id, :text, null: false
      add :scope, :text, null: false
      add :scope_ref, :text, null: false
      add :from_sequence, :bigint
      add :to_sequence, :bigint
      add :status, :text, null: false, default: "building"
      add :bundle_sha256, :binary
      add :bundle_path, :text
      add :signature, :binary
      add :key_id, :text
      add :assurance_level, :text
      add :anchor_ids, {:array, :uuid}, default: []
      add :failure_reason, :text
      add :trace_id, :text, null: false
      add :span_id, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "audit_exports_tenant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(:audit_exports, :audit_exports_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )

    execute("""
    CREATE FUNCTION audit_exports_terminal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION '% is append-only: % rejected (invocations cannot be deleted)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.status IN ('completed', 'failed') THEN
        RAISE EXCEPTION '% row % is terminal: update rejected', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF (to_jsonb(NEW) - ARRAY['status', 'from_sequence', 'to_sequence', 'bundle_sha256', 'bundle_path', 'signature', 'key_id', 'assurance_level', 'anchor_ids', 'failure_reason', 'updated_at', 'trace_id', 'span_id']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'from_sequence', 'to_sequence', 'bundle_sha256', 'bundle_path', 'signature', 'key_id', 'assurance_level', 'anchor_ids', 'failure_reason', 'updated_at', 'trace_id', 'span_id']) THEN
        RAISE EXCEPTION '% row %: immutable column changed', TG_TABLE_NAME, OLD.id
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END;
    $$
    """)

    execute("""
    CREATE TRIGGER audit_exports_guard_row BEFORE UPDATE OR DELETE ON audit_exports FOR EACH ROW EXECUTE FUNCTION audit_exports_terminal_immutable()
    """)

    execute("""
    CREATE TRIGGER audit_exports_guard_truncate BEFORE TRUNCATE ON audit_exports FOR EACH STATEMENT EXECUTE FUNCTION audit_exports_terminal_immutable()
    """)

    create table(:audit_signing_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :key_id, :text, null: false
      add :algorithm, :text, null: false, default: "ed25519"
      add :public_key, :binary, null: false
      add :status, :text, null: false, default: "active"
      add :activated_at, :utc_datetime_usec, null: false
      add :retired_at, :utc_datetime_usec
      add :revocation_reason, :text
      add :trace_id, :text, null: false
      add :span_id, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:audit_signing_keys, [:status],
             name: "audit_signing_keys_one_active_index",
             where: "(status = 'active')"
           )

    create unique_index(:audit_signing_keys, [:key_id],
             name: "audit_signing_keys_unique_key_id_index"
           )

    create constraint(:audit_signing_keys, :audit_signing_keys_public_key_length,
             check: """
               octet_length(public_key) = 32
             """
           )

    create constraint(:audit_signing_keys, :audit_signing_keys_trace_ids,
             check: """
               trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32) AND span_id ~ '^[0-9a-f]{16}$' AND span_id <> repeat('0', 16)
             """
           )
  end

  def down do
    drop_if_exists constraint(:audit_signing_keys, :audit_signing_keys_trace_ids)

    drop_if_exists constraint(:audit_signing_keys, :audit_signing_keys_public_key_length)

    drop_if_exists unique_index(:audit_signing_keys, [:key_id],
                     name: "audit_signing_keys_unique_key_id_index"
                   )

    drop_if_exists unique_index(:audit_signing_keys, [:status],
                     name: "audit_signing_keys_one_active_index"
                   )

    drop table(:audit_signing_keys)

    execute("""
    DROP TRIGGER audit_exports_guard_truncate ON audit_exports
    """)

    execute("""
    DROP TRIGGER audit_exports_guard_row ON audit_exports
    """)

    execute("""
    DROP FUNCTION audit_exports_terminal_immutable()
    """)

    drop_if_exists constraint(:audit_exports, :audit_exports_trace_ids)

    drop constraint(:audit_exports, "audit_exports_tenant_id_fkey")

    drop table(:audit_exports)

    execute("""
    DROP TRIGGER audit_anchors_guard_truncate ON audit_anchors
    """)

    execute("""
    DROP TRIGGER audit_anchors_guard_row ON audit_anchors
    """)

    execute("""
    DROP FUNCTION audit_anchors_append_only()
    """)

    drop_if_exists constraint(:audit_anchors, :audit_anchors_trace_ids)

    drop_if_exists constraint(:audit_anchors, :audit_anchors_signature_length)

    drop_if_exists constraint(:audit_anchors, :audit_anchors_hash_lengths)

    drop_if_exists constraint(:audit_anchors, :audit_anchors_valid_range)

    drop constraint(:audit_anchors, "audit_anchors_prior_anchor_id_fkey")

    drop constraint(:audit_anchors, "audit_anchors_tenant_id_fkey")

    alter table(:audit_anchors) do
      remove :prior_anchor_id
    end

    drop_if_exists unique_index(:audit_anchors, [:tenant_id, :anchor_number],
                     name: "audit_anchors_unique_number_index"
                   )

    drop_if_exists unique_index(:audit_anchors, [:tenant_id, :to_sequence],
                     name: "audit_anchors_unique_head_index"
                   )

    alter table(:audit_anchors) do
      remove :tenant_id
      remove :inserted_at
      remove :span_id
      remove :trace_id
      remove :trigger
      remove :sdr_agent_git_sha
      remove :canonicalization_version
      remove :key_status_at_signing
      remove :key_id
      remove :signature
      remove :anchor_hash
      remove :statement_bytes
      remove :prior_anchor_hash
      remove :head_event_hash
      remove :to_sequence
      remove :from_sequence
      remove :anchor_number
    end

    execute("""
    DROP TRIGGER anchor_sink_receipts_guard_truncate ON anchor_sink_receipts
    """)

    execute("""
    DROP TRIGGER anchor_sink_receipts_guard_row ON anchor_sink_receipts
    """)

    execute("""
    DROP FUNCTION anchor_sink_receipts_append_only()
    """)

    drop_if_exists constraint(:anchor_sink_receipts, :anchor_sink_receipts_trace_ids)

    drop constraint(:anchor_sink_receipts, "anchor_sink_receipts_anchor_id_fkey")

    drop constraint(:anchor_sink_receipts, "anchor_sink_receipts_tenant_id_fkey")

    alter table(:anchor_sink_receipts) do
      modify :anchor_id, :uuid
    end

    drop table(:audit_anchors)

    drop table(:anchor_sink_receipts)
  end
end
